zeldaret/mm

Makefile
Changes:
- init now explicitly calls make on each target. This allows it to work with -j.
- setup now calls extract_rom.py, simplifying the setup process. Since extract_rom expects a path to the rom to extract, I gave a default which matches other decomp projects, with the option to override if desired.
- all now explicitly builds the uncompressed rom, then the compressed one. This fixes a problem when using -j where the compressed rom could finish building first, then fail and stop the uncompressed rom from finishing. Since the uncompressed rom was never built, you could not use first_diff.py to see what was wrong. This makes it slightly slower, but only by a few seconds in most cases.
=> Fix several issues with the makefile

tools/overlay.py
Fixing an issue that has been on my TODO list for awhile. Relocations are always in the order of .text, .data, then .rodata. Sometimes objects don't order the relocation sections that way, which causes our script to produce non-matching overlays. Fix it by just iterating over those sections in the expected order.
=> Fix ordering of relocations in overlay

include/z64.h, src/code/z_snap.c
Makes ACTIVE_CAM macro usable.
func_8013A530 in src/code/z_snap.c changes to use new GlobalContext struct.
=> GlobalContext: unwrap CameraContext

include/PR/ultratypes.h
It was broken before and required me to use int instead of s32. This fixes it though (copied from OoT)
=> Fixed ultratypes.h

tools/depend.py
This fixes a couple of issues that people were having, such as when there was a space before the `#pragma` or having the path to the assembly file formatted oddly.
=> Improve the robustness of depend.py

tools/overlayhelpers/actor_symbols.py
The `decomp/` directory is no longer generated as of this recent PR  https://github.com/zeldaret/mm/pull/117. This breaks the `tools/overlayhelper` scripts via the actor_symbols.py, so a quick fix is made. 
I would expect `baserom/` would be fine as well as `build/baserom/`, but I arbitrarily went with the latter. Let me know if you prefer the former.
This may also be affected (and break again) by https://github.com/zeldaret/mm/pull/121
=> Update actor symbols

.gitignore, Makefile, assets/.gitignore, extract_assets.py, linker_scripts/code_script.txt
- Extract the assets to `assets/` instead of `assets/src/`.
- For `scenes`, they would be extracted to `assets/scenes/`
- Do the extraction in the `make setup` step instead of doing it in the build step.
- Port `extract_assets.py`. This is done to prevent increasing the complexity of the Makefile.
=> Extract assets in `make setup`, don't extract them to `assets/src/` and build them in `make`

Makefile
- Add `cp -r baserom/ build/baserom/` at the end of the `setup` target.
- This is just a hacky way to fix the dependency bug we currently have. Hopefully somebody will figure out a proper way to fix this soon.
- Add an `assembly` target.
- This should allow to not regenerate every assembly every time `make` is run, making possible to edit assembly files locally to do your own tests.
- To regenerate the assemblies before compiling, just run `make assembly` before running `make`.
- Small cleaning of the `Makefile`.
=> Hotfix: Fix running `make init` without `-jN`

.gitmodules, Makefile, tools/gen_mips_to_c_context.py, tools/m2ctx.py, tools/overlayhelpers/ichaindis.py
Using `/usr/bin/env python3` is preferred over `/usr/bin/python3` because it is compatible with virtualenvs, etc. It picks the version of `python3` currently on the `PATH`, rather than the system-wide default.
For the git submodules, I had two issues (at least on git 2.7.4 from Ubuntu 16.04, which is admittedly pretty old!)
- The ZAPD repo is currently pointing at a commit not on the master branch, which has to be specifically fetched. Adding `--remote` to the update command fixes this.
- The decomp-permuter has primary branch `main` not `master` like this repo, so this has to be specified in `.gitmodules` when using `--remote`.
=> Small env fixes: git submodules & python3

tools/overlayhelpers/data_parser.py
---
This has two modes: extern and arrays. Extern just gives a list of externed data. Arrays gives s32 arrays (and floats are labelled as well).
=> Added data_parser.py to assist in moving data over to c files more easily

include/z64cutscene.h
---
ZAPD will start extracting cutscenes as `CutsceneData[]` instead of `s32[]` when [ZAPD PR 151](https://github.com/zeldaret/ZAPD/pull/151) is merged.
Since MM doesn't have this type yet, that PR is failing and can't be merged yet.
=> Add `CutsceneData` struct

Makefile
---
As we discussed in the discord server, it isn't a good idea to constantly check which C files should be recompiled when a header is  changed at this stage of this project since every header is included everywhere, so that check is now removed.
I also decided to remove most of the `@` at each command so we can see what's actually going in each step of the build process (instead …
=> Remove header dependencies checks

Makefile
---
Change Makefile so that compression only starts if checksum matches, or compare is turned off.
Relevant Discord discussion https://discord.com/channels/688807550715560050/740615251011174401/874027259634286592
=> Update makefile so compression only starts if checksum matches

src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.c
---
Master is currently broken because of a few functions renamed.
=> Fix renamed functions in EnDodongo

src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.c, src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.c, src/overlays/actors/ovl_En_Dnq/z_en_dnq.c, src/overlays/actors/ovl_En_Holl/z_en_holl.c, src/overlays/actors/ovl_En_Pametfrog/z_en_pametfrog.c
---
When I was working on ArrowIce, I noticed that running `./format.sh` would change files outside of the ones I was touching. Turns out, even in `master` right now, there are some files that have some misformatted code. To make this PR, all I did was run `./format.sh` in `master`, then make a new branch and push it up.
=> Fix some misformatted files in current master

spec, src/libultra/gu/position.c
---
I have a nasty feeling we're going to need to have a Big Matrix Rename™️ in MM as well, so just copying this over from OoT for now.
Bit of a shame that none of our favourite angle conversion macros will work here.
=> position OK

Makefile, diff_settings.py
---
Since `-g3` produces a very large `.mdebug` section, MM currently produces much larger object files (`.o` files, to be unambiguous), and often it takes forever to link. Therefore @Thar0 and I came up with a way to remove the `.mdebug` section from the files at build time. 
- This speeds up linking considerably, dwarfing the earlier timeloss from the extra `objdump`ing required, …
=> Remove `.mdebug` sections by default

include/functions.h, spec, src/overlays/actors/ovl_Obj_Aqua/z_obj_aqua.c, src/overlays/actors/ovl_Obj_Aqua/z_obj_aqua.h
---
Bottled water has it's damage flags set to 0xF7CFFFFF interestingly enough, acting as every damage type except normal shield, light ray, and whatever the 28th bit flag is. Unfortunately it only has AT_TYPE_OTHER set, and most colliders don't check for this type.
Sun blocks have AC_TYPE_OTHER set and check for light arrows, so bottled water can melt them. I haven't exhaustively …
=> obj_aqua OK

include/functions.h, src/libultra/os/sethwinterrupt.c
---
Last function in libultra/os matched. 2/6 libultra folders complete.
=> sethwinterrupt OK

src/code/game.c, src/overlays/actors/ovl_Door_Ana/z_door_ana.c, src/overlays/actors/ovl_En_Clear_Tag/z_en_clear_tag.c, src/overlays/actors/ovl_En_In/z_en_in.c, src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c, src/overlays/actors/ovl_En_Minislime/z_en_minislime.c, src/overlays/actors/ovl_En_Railgibud/z_en_railgibud.c, src/overlays/actors/ovl_Obj_Raillift/z_obj_raillift.c
---
In my PR for Obj_Etcetera, I fixed a match that involved a dummy label by using a scoped pad. I found out that a few other dummy labels in the codebase can be fixed the same way:
- For the actors, I'm pretty sure all of them are "true" matches.
- For game.c, I'm not sure if either of the things I changed are a "true" match or not, but they get rid of the dummy labels. If people …
=> Fix some dummy label matches

src/libultra/os/resetglobalintmask.c
---
The most interesting thing about this file is that `register` makes a significant difference to the codegen.
=> resetglobalintmask OK

src/code/z_prenmi.c, src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
---
PreNMI_Draw just needed the DISPS macros to match, so I added them. Also did ArmsHook, although I had to fake-match it a bit.
=> Match last function in z_prenmi, add DISPS macros to ArmsHook

src/libultra/os/setglobalintmask.c
---
Even simpler than its resetting colleague.
=> setglobalintmask OK

Makefile
---
This will stop `make init` from compressing the rom twice, by having diff-init just depend on the uncompressed rom.
=> Update diff-init to be dependent on just the uncompressed rom

include/functions.h, spec, src/code/title_setup.c, src/code/z_common_data.c, tools/disasm/functions.txt
=> Common data OK

include/functions.h, src/code/z_skelanime.c, tools/disasm/functions.txt
---
This is the only non matching left in z_skelanime.
I matched this one in OoT, and I just noted Lucas didn't update this function when he did his skelanime PR, so here we are.
The function is completely unused. It goes back to the `object_human` era of OoT, which is the only OoT object which still uses this old format.
This looks like a fake match for a loop unroll. If anybody …
=> Match `SkelAnime_GetFrameDataLegacy`

src/code/z_en_item00.c
---
This is a little awkward of a match, but it's the best I could find. I'm almost certain this function needs a `params` temp somewhere to match, and this seemed to be the best place it could be that still worked.
=> Match EnItem00_Update

include/functions.h, src/libultra/io/spsetpc.c
=> osspsetpc OK

include/ultra64/gs2dex.h, include/z64.h, src/boot_O2_g3/idle.c, src/libultra/gu/guS2DInitBg.c
---
Also added the required gbi header. For now I put it in z64.h, but it's likely going to be used so little that it's probably better to be included filewise when we sort the headers out.
=> guS2DInitBg OK

Makefile, tools/disasm/disasm.py
---
This PR adds multiprocessing to the disassembly script. On my machine, this brings the runtime down from 2 minutes on a single core to 45 seconds when run with 8 processes.
I made my best attempt to avoid changing the code's structure. Therefore there is a bit of a hacky solution for dealing with the multiple sets of symbols (see `update_symbols_from_dict`). If anyone has a …
=> Add multiprocessing to disassembly script

src/libultra/io/pfsdeletefile.c
---
As with #422 and #423 , rewrote the ifs to separate the assignments.
=> pfsdeletefile OK

src/libultra/io/pfsfilestate.c
---
I wrote the `if ((ret = ...) != 0)`s as
```c
ret = ...;
if (ret != 0)
```
because I think it's clearer.
=> pfsfilestate OK

src/overlays/actors/ovl_En_Hg/z_en_hg.c
---
After the enum PR was merged, I went and updated my existing PRs to use it. In the process of doing so, I noticed there was exactly one place in the codebase that used `INV_CONTENT` *without* using an appropriate item enum, which was En_Hg. So this PR just changes the 0x41 to `ITEM_MASK_GIBDO` to match all other uses of `INV_CONTENT`.
=> Use ITEM_MASK_GIBDO enum in En_Hg

tools/warnings_count/check_new_warnings.sh
---
Since I feel most warnings will show up in the actual build (not setup or disasm), changed the warnings script to just check for build warnings by default. I have also added an option to still check warnings from start to finish for those cases where it still matters.
=> Add ability to warnings script to just check building (not setup or disasm)

tools/m2ctx.py
---
This PR adds the ability to alter m2ctx output, right now just to edit actorLists[2] to return a Player* under a `--fix` or `-f` flag.
=> m2ctx: Optionally return Player* for Player accesses

spec, src/overlays/actors/ovl_En_Invisible_Ruppe/z_en_invisible_ruppe.c, src/overlays/actors/ovl_En_Invisible_Ruppe/z_en_invisible_ruppe.h
=> EnInvisibleRuppe OK

src/libultra/io/viswapcontext.c
---
Not sure if we want to keep the __ on structs like `__OSViContext`, but that can be decided later.
=> viswapcontext OK

Makefile
---
Made a few efficiency changes to the Makefile:
- Only copy the baserom files that are actually needed (58 instead of 1532).
- Remove use of `iconv` on the data before it's assembled: there is no data that needs this any more.
- Remove the optimisation flags from the assets: these won't do anything to data, but `-g3` at least will needlessly bloat the symbol tables in the files …
=> Three Makefile tweaks

spec, src/overlays/actors/ovl_En_Talk/z_en_talk.c, src/overlays/actors/ovl_En_Talk/z_en_talk.h
---
Not too much to go by for naming the two additional functions, I'm assuming `func_80BDE090` has to do with displaying the reticule but I'm not sure what the context is for switching between the two (maybe when you're reading the associated text?)
=> ovl_En_Talk OK

assets/xml/objects/object_mag.xml
---
Doing the textures first, because I expect them to be considerably easier than the actual actor.
=> Name textures in object_mag

assets/xml/interface/week_static.xml, assets/xml/misc/story_static.xml
---
Recommend looking at the story_static images, they're really detailed and vibrant (being the full 320 by 240)
=> Two small xmls for parameter-related asset files

tools/m2ctx.py
=> Fix m2ctx for new z_actor

assets/xml/objects/object_bigpo.xml, assets/xml/objects/object_bigslime.xml, assets/xml/objects/object_gmo.xml, assets/xml/objects/object_mag.xml, assets/xml/objects/object_tokei_step.xml
---
Some assets have been already merged without a comment at the top describing what they are, so I included that comment. I didn't have a ton of context on some of these, so if you can think of a better description, feel free to post it. I also used "tlut" instead of "palette" on object_gmo, since we decided we wanted to standardize on "tlut".
=> Bring merged assets up to current standards

tools/ZAPD/.gitrepo, tools/ZAPD/ZAPD/ZTexture.cpp
=> Fix ZAPD `filesystem` usage

src/boot_O2_g3/z_std_dma.c, src/code/z_actor.c, src/code/z_eff_tire_mark.c, src/overlays/actors/ovl_En_Fsn/z_en_fsn.c, src/overlays/actors/ovl_En_Giant/z_en_giant.c
---
This PR fixes most of the dummy label matches currently in the repo. It doesn't fix the one in title_setup.c (because we probably need more data from other gamestate functions to understand what it's doing), nor does it fix the one in invadepoh (because I can't figure it out; here's the scratch if you want to bang your head against it: https://decomp.me/scratch/JVMlL)
Like I …
=> Fix some more dummy label matches

tools/ZAPD/.gitrepo, tools/ZAPD/ZAPD/WarningHandler.cpp, tools/ZAPD/ZAPD/ZAnimation.cpp, tools/ZAPD/ZAPD/ZCollision.cpp, tools/ZAPD/ZAPD/ZCutscene.cpp, tools/ZAPD/ZAPD/ZFile.cpp, tools/ZAPD/ZAPD/ZFile.h, tools/ZAPD/ZAPD/ZLimb.cpp, tools/ZAPD/ZAPD/ZLimb.h, tools/ZAPD/ZAPD/ZSkeleton.cpp, tools/ZAPD/ZAPD/ZSkeleton.h, tools/ZAPD/ZAPD/ZTexture.cpp, tools/ZAPD/ZAPD/ZTexture.h, tools/ZAPD/ZAPDUtils/Utils/BitConverter.h, tools/ZAPD/ZAPDUtils/Utils/StringHelper.h, tools/ZAPD/docs/zapd_extraction_xml_reference.md
---
Fixes a problem described in https://github.com/zeldaret/ZAPD/pull/236
Also includes the limb enum generation from https://github.com/zeldaret/ZAPD/pull/236
=> ZAPD hotfix

include/variables.h, spec, src/libultra/io/contramread.c, tools/disasm/variables.txt
---
I did not rename the structs or variables in the header, but adapted the function to work with the current ones, since @Thar0 will be cleaning up libultra once it's all decompiled anyway. (And after this and contramwrite, it's just voice left)
=> contramread OK

include/variables.h, src/libultra/io/contramwrite.c, tools/disasm/variables.txt
---
And the other one. Same remarks as #577 apply.
=> contramwrite OK

assets/xml/overlays/ovl_Arrow_Ice.xml, src/overlays/actors/ovl_Arrow_Ice/z_arrow_ice.c
---
This PR does two simple things:
- Adds a comment to the top of the ovl_Arrow_Ice XML
- Updates the names of the display lists to use the "material"/"model" naming scheme like OoT now does from: https://github.com/zeldaret/oot/pull/985
=> Add comment to Arrow_Ice xml and update DL names

assets/xml/objects/gameplay_keep.xml, src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c, src/overlays/actors/ovl_En_Encount2/z_en_encount2.c
---
There was some talk about how the sun worked in OoT today, so I ported over the OoT names into MM. According to Emil, these should actually be a single 64x64 texture, but that doesn't quite work with ZAPD, so I left them as three separate textures for now.
=> Document sun textures/displaylist

tools/disasm/disasm.py
---
This gives you the ability to disassemble specific files with disasm like `./tools/disasm/disasm.py --files Encount2 Obj_Boat Ending_Hero2`/ There's no change if you don't use `--files`.
The use-case for this is where you're switching between branches and don't want to fully disassemble. 
Currently: On branch A with modified file names -> make OK -> switch to branch B -> make …
=> Optional file disasm

Jenkinsfile, spec, tools/reloc_spec_check.sh
---
I made a small script which checks for relocs to be correctly used on the spec depending if the overlay is matched, has NON_MATCHINGs and/or NON_EQUIVALENTs
The script performs the following checks:
- The extracted reloc isn't being used on the spec if the overlay has no other GLOBAL_ASM left (it has been matched).
- Warn if an overlay is using both NON_MATCHING and …
=> Script for checking relocs correctly updated on spec

src/overlays/actors/ovl_Bg_F40_Switch/z_bg_f40_switch.c, src/overlays/actors/ovl_Bg_F40_Switch/z_bg_f40_switch.h
---
mzx pointed out in discord that this file was using `this` for the params macro instead of `thisx`, so I went and fixed that. While I was in there, I noticed that the `DynaPolyActor*` was called `actor` instead of `dyna`, so I fixed that too.
=> Fix two small things in Bg_F40_Switch

assets/xml/objects/object_dog.xml, src/overlays/actors/ovl_En_Dg/z_en_dg.c, src/overlays/actors/ovl_En_Dg/z_en_dg.h, src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c, src/overlays/actors/ovl_En_Racedog/z_en_racedog.c, src/overlays/actors/ovl_En_Racedog/z_en_racedog.h
---
Was sort of floundering trying to figure out where to start documenting the Dg/Racedog/Aob blob, and I figured that documenting the object would give me a decent place to start. A lot of this was the same as OoT, but I double-checked everything just to be sure. I don't really like the names of `gDogJumpAnim`, `gDogJump2Anim`, and `gDogLongJumpAnim`, but as I document dogs more, …
=> Document object_dog

Makefile, diff_settings.py, include/macro.inc, tools/asm-differ/.gitrepo, tools/asm-differ/.pre-commit-config.yaml, tools/asm-differ/README.md, tools/asm-differ/diff.py, tools/asm-processor/asm_processor.py, tools/asm-processor/build.py, tools/asm-processor/prelude.inc, tools/disasm/disasm.py, tools/disasm/mips_isa.py
---
Use the o32 ABI names for floating-point registers in the assembly. Finally the float registers usage makes some sense!
This involved changing quite a lot of tools:
- Add the aliases to `macro.inc`.
- Add support to `diff.py`.
- Add support to `mips_to_c`.
- Change the disassembler to enable the choice of abi or numeric names for float registers. This required tweaking the …
=> ABI FPR names

assets/xml/objects/object_boss02.xml, src/overlays/actors/ovl_Boss_02/z_boss_02.c, src/overlays/actors/ovl_Boss_02/z_boss_02.h, src/overlays/actors/ovl_En_Tanron5/z_en_tanron5.c
---
Relatively straightforward object, though the dust thing took me some time and testing to figure out. I couldn't grab animation names from MM3D because the way Twinmold's rig is set up in that game is so different; his head and body are just a single skeleton instead of being split up like in MM64.
=> Document object_boss02 (Twinmold assets)

assets/xml/objects/object_okuta.xml, assets/xml/overlays/ovl_En_Syateki_Okuta.xml, src/overlays/actors/ovl_En_Syateki_Okuta/z_en_syateki_okuta.c, src/overlays/actors/ovl_En_Syateki_Okuta/z_en_syateki_okuta.h
---
Another relatively simple object that's mostly an OoT port. I also documented the assets within ovl_en_syateki_okuta, since that actor is really my motivation for doing this. I deleted the Vtx array in the overlay because ZAPD can autogenerate it and I don't care enough to name it.
=> Document object_okuta and ovl_en_syateki_okuta assets

src/overlays/actors/ovl_Bg_Hakugin_Bombwall/z_bg_hakugin_bombwall.c, src/overlays/actors/ovl_Bg_Hakugin_Bombwall/z_bg_hakugin_bombwall.h
After removing a dummy label match in EnInvadepoh, I thought that most of them were gone, but one snuck in without me noticing. This was a fun one to solve. My thought process went like this:
- `BgHakuginBombwallUnkFunc` almost certainly takes `this`, not `thisx`, since both `func_80ABCB5C` and `func_80ABCC00` immediately made a `this` temp anyways.
- Just doing that + introducing the right `requiredScopeTemp` removes the dummy label and fixes `func_80ABCC00`, but at this point `func_80ABCB5C` was pretty messed up.
- I solved that by using a pattern that OoT3D taught me: the lowly `thisx` temp. In OoT3D, this is required in a bunch of different places to match, so I think it was simply a common pattern they used. It works perfectly to solve the problem I was seeing in `func_80ABCB5C`.
=> Remove a dummy label match in BgHakuginBombwall

README.md
Noticed the link was pointing to the original `CONTRIBUTING.md` path when trying to get back into decomp after a break. Updated it to match the link further down in the README.
=> README.md "How to Contribute" wrong path

assets/xml/objects/gameplay_keep.xml
Documents the rest of the assets in gameplaykeep used by EffectSbn, including ones that look unused.
=> Effect Sbn Asset Docs

assets/xml/objects/object_thiefbird.xml, src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.c, src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.h
`gTakkuriStolenGreatFairySwordBladeGildedSwordPommelAndGuardTex` is just *barely* below the max number of characters a symbol can have. It, along with some of the other textures used by stolen items, is hard to name because of a surprising amount of reuse.
=> object_thiefbird (Takkuri) documented

Makefile
On non-english system, the `diff.py` script could not be able to work due to the map file being created using the system localization.
As the `search_map_file()` function of the script is searching for "_load address_" words, map files created using non-english localization will not be read correctly, causing the script to fail with `Not able to find .o file for function.`.
A workaround is then to set the `LANG` environnement variable to `en_US` or `C` to ensure the map files being created in english.
=> set LANG variable in Makefile

assets/xml/objects/gameplay_keep.xml, src/overlays/actors/ovl_En_Test6/z_en_test6.c
I was talking about EnTest6 with someone in discord today and noticed that the assets for the clock when you play Song of Time were not documented. They were pretty easy to figure out, so I just quickly knocked them out.
=> Document Song of Time Clock assets in gameplay_keep

assets/xml/objects/object_gs.xml, src/overlays/actors/ovl_En_Gs/z_en_gs.c
I needed an easy one to cool down after object_dblue_object. Despite the object being identical to its OoT counterpart, I deliberately deviated on one of the names. In OoT, they call this `gGossipStoneSquishedDL`:
What I found out in testing is that it's *actually* the bottom of the Gossip Stone. In Z64Utils, you can see the "main" Gossip Stone DL has no bottom like so:
You don't usually see the bottom of the Gossip Stone, but you can spot it when it launches into the air after being hit by an explosive. If I had to speculate, I'm guessing the original DL was made first, and then when they added the ability to launch it into the air, they quickly patched the hole at the bottom with the other DL. I'll port these names over to OoT when this gets merged.
=> Document object_gs (Gossip Stone)

assets/xml/objects/gameplay_dangeon_keep.xml, assets/xml/objects/object_bdoor.xml, src/code/z_actor.c, src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
Did some very minor cleanup on gameplay_dangeon_keep too; I renamed `gDoorChainsDL` to `gDoorChainDL` because the DisplayList is only a single chain, and it's the actor that's responsible for drawing multiple chains:
=> Document object_bdoor (Boss Doors)

src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c, src/overlays/actors/ovl_En_Arrow/z_en_arrow.c, src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.c, src/overlays/actors/ovl_En_Bom/z_en_bom.c, src/overlays/actors/ovl_En_Boom/z_en_boom.c, src/overlays/actors/ovl_En_Elf/z_en_elf.c, src/overlays/actors/ovl_En_Fishing/z_en_fishing.c, src/overlays/actors/ovl_En_Peehat/z_en_peehat.c, src/overlays/actors/ovl_En_Pp/z_en_pp.c, src/overlays/actors/ovl_En_Rat/z_en_rat.c, src/overlays/actors/ovl_En_Wood02/z_en_wood02.c
I was looking at ArmsHook recently, and I noticed that instead of using `ACTOR_FLAG_2000`, they used 0x2000 in some places. This PR tries to clean up cases like this and use `ACTOR_FLAG_X` whenever possible. I may have missed something, but at least it's a start.
=> Cleanup some "raw" actor flags

src/overlays/actors/ovl_Bg_Ikana_Rotaryroom/z_bg_ikana_rotaryroom.c, src/overlays/actors/ovl_Boss_03/z_boss_03.c, src/overlays/actors/ovl_Dm_An/z_dm_an.c, src/overlays/actors/ovl_Dm_Gm/z_dm_gm.c, src/overlays/actors/ovl_En_Hs2/z_en_hs2.c, src/overlays/actors/ovl_En_Tag_Obj/z_en_tag_obj.c, src/overlays/actors/ovl_En_Tanron6/z_en_tanron6.c, src/overlays/actors/ovl_En_Water_Effect/z_en_water_effect.c, src/overlays/actors/ovl_En_Water_Effect/z_en_water_effect.h, src/overlays/actors/ovl_Item_Inbox/z_item_inbox.c, src/overlays/actors/ovl_Obj_Dowsing/z_obj_dowsing.c
A filled in a few blank descriptions, and fixed some other ones. Some notes:
- Tanron6 had a ridiculous CloudModding description, which is what motivated me to begin with
- DmGm is indeed a complete duplicate of DmAn. However, in our code, one line differed, so I went and made that line no longer differ. Let me know if you prefer the way it was before, in which case I'll propagate that change to the other one.
- I did some minor documentation of WaterEffect to give it a better description. I also used its type enum in all applicable places.
=> Fix up some actor descriptions

assets/xml/objects/gameplay_keep.xml
In OoT, there exist multiple joint tables used for the pause menu; they're located right above the player animations within `gameplay_keep`. I noticed that in MM, we had an unknown blob above the player animations, and some it suspiciously looked like joint table data.
What was strange here is that there wasn't enough room for all five joint tables from OoT. I did some more digging and I found out that, despite what the Deku Stick DL is asking for, the Deku Stick texture is *actually* an 8x8 texture. Defining it as such makes it so that all give OoT pause menu joint tables can be extracted. This means that the Deku Stick, in-game, will render some garbage based on the Child Link joint tables. I wasn't sure how to document that, though; I would slap a `@bug` above it normally, but the …
=> Document leftover pause joint tables

assets/xml/objects/gameplay_keep.xml, assets/xml/objects/object_zog.xml, src/overlays/actors/ovl_En_Torch2/z_en_torch2.c
To get in the spooky spirit, I decided to take a look at some of MM's creepier assets; the shells left behind when you play the Elegy of Emptiness. Note that the Zora shell's guitar shares textures with Mikau's grave, so the two should share names as well.
=> Document Elegy of Emptiness shell assets in gameplay_keep

include/functions.h, include/z64.h, include/z64scene.h, src/code/z_elf_message.c, src/code/z_scene.c, src/overlays/actors/ovl_En_Elf/z_en_elf.c, tools/disasm/functions.txt
This renames the ElfMessage system to QuestHint, as was just done in OoT.
Thankfully in this game it is not an elborate scripting system, its much simpler.
I opted to rename `ElfMessage_GetFirstCycleHint` to `QuestHint_GetTatlTextId` for parallelism to OoT's `QuestHint_GetNaviTextId`.
Imo one could easily expand this to be for more than first cycle in a modding scenario, and all that really matters is that it gets used for tatls c up text (the functionality is still there in en_elf, nothing limits it to first cycle). So the first cycle aspect isnt as important to mention in the function name. But I did note it in the function comment.
=> Rename elf_message to QuestHint (sync with oot)

assets/xml/objects/object_boss01.xml, assets/xml/objects/object_bsmask.xml, assets/xml/objects/object_ob.xml, src/overlays/actors/ovl_En_Js/z_en_js.c
Had to engage in more speculation than normal on this one in order to guess at the original names, but I think I'm right about the final set of animations just being `jmp_stop` plus a number. There's an array in Boss01's data (`D_809D7CF4` if you're interested) that's just all of those animations in order (minus `jmp_stop02`, which is used for the intro), and the gaps in the animation names perfectly line up if you just keep sequentially counting up.
Since Odolwa has a lot of dancing/hopping animations that are fairly similar, I'll post GIFs of them along with my names; feel free to invent better names based on your own observations:
`gOdolwaReadyAnim`:
`gOdolwaSpinSwordAnim`:
`gOdolwaVerticalHopAnim`:
`gOdolwaHipShakeAnim`:
`gOdolwaUpAndDownDanceAnim`:
`gOdolwaArmSwingDanceAnim`: …
=> Document object_boss01 (Odolwa)

requirements.txt
`pyelftools` is needed by `z64compress_wrapper.py`. Without this package, the compression step would fail.
=> Add `pyelftools` back to `requirements.txt`

assets/xml/objects/object_ah.xml, assets/xml/objects/object_al.xml, assets/xml/objects/object_am.xml, assets/xml/objects/object_an1.xml, assets/xml/objects/object_an2.xml, assets/xml/objects/object_an3.xml, assets/xml/objects/object_an4.xml, assets/xml/objects/object_and.xml, assets/xml/objects/object_ani.xml, assets/xml/objects/object_astr_obj.xml
For a long time, most people have just asked me what the original asset names from MM3D are, rather than finding the names themselves. This is, overall, fine, but it has a "bus factor" of 1; if I'm not around, you can't get the names from me. So I've decided to just put the original asset names in for *every* object so that people don't have to rely on me.
This PR does every single object whose name starts with `object_a*`. Thanks, as always, to @emilybrooks for patiently answering my Japanese questions.
=> Add original asset names to all `object_a*` files

assets/xml/objects/object_boss07.xml
I did this in @petrie911's Majora branch a long time ago: https://github.com/petrie911/mm/pull/2
I figured I'd bring it over to `master` for two reasons:
- I want to document the original name of every single asset, if possible, so people don't have to ask me about them. I already documented the original asset names for this object, so I figured I'd just grab the whole thing.
- This way, when petrie PR's Majora, reviewers won't have to review work that petrie himself didn't do.
=> Document object_boss07 (Majora assets)

assets/xml/objects/object_bai.xml, assets/xml/objects/object_bal.xml, assets/xml/objects/object_bba.xml, assets/xml/objects/object_bee.xml, assets/xml/objects/object_bg.xml, assets/xml/objects/object_bh.xml, assets/xml/objects/object_big_fwall.xml, assets/xml/objects/object_bigicicle.xml, assets/xml/objects/object_bigokuta.xml, assets/xml/objects/object_bigpo.xml, assets/xml/objects/object_bigslime.xml, assets/xml/objects/object_bji.xml, assets/xml/objects/object_bjt.xml, assets/xml/objects/object_boj.xml, assets/xml/objects/object_bombf.xml, assets/xml/objects/object_bombiwa.xml, assets/xml/objects/object_boss05.xml, assets/xml/objects/object_botihasira.xml, assets/xml/objects/object_box.xml, assets/xml/objects/object_bsb.xml, assets/xml/objects/object_bsmask.xml, assets/xml/objects/object_cha.xml, assets/xml/objects/object_comb.xml, assets/xml/objects/object_crow.xml, assets/xml/objects/object_cs.xml, assets/xml/objects/object_ctower_rot.xml, assets/xml/objects/object_os_anime.xml, assets/xml/overlays/ovl_En_Sth.xml, assets/xml/overlays/ovl_En_Sth2.xml
Specifically, I did parts of `object_os_anime`, as well as all of `ovl_En_Sth` and `ovl_En_Sth2`, since their animations were moved to `zelda2_cne` and `zelda2_boj` in MM3D.
=> Add original asset names for all `object_b*` and `object_c*` files (and some related stuff)

assets/xml/objects/object_efc_star_field.xml, assets/xml/objects/object_efc_tw.xml, assets/xml/objects/object_eg.xml, assets/xml/objects/object_ending_obj.xml, assets/xml/objects/object_f40_obj.xml, assets/xml/objects/object_f40_switch.xml, assets/xml/objects/object_f52_obj.xml, assets/xml/objects/object_f53_obj.xml, assets/xml/objects/object_fall.xml, assets/xml/objects/object_fall2.xml, assets/xml/objects/object_famos.xml, assets/xml/objects/object_fb.xml, assets/xml/objects/object_firefly.xml, assets/xml/objects/object_fish.xml, assets/xml/objects/object_flowerpot.xml, assets/xml/objects/object_fr.xml, assets/xml/objects/object_fsn.xml, assets/xml/objects/object_fu.xml, assets/xml/objects/object_fu_kaiten.xml, assets/xml/objects/object_fu_mato.xml, assets/xml/objects/object_funen.xml, assets/xml/objects/object_fusen.xml, assets/xml/objects/object_fwall.xml
Pretty similar to my other PRs like this.
"But wait!" you might say. "Where's `object_fz`?" Well, MM3D's `zelda_fz.gar.lzs` looks like this:
There are two things to note:
- The names actually look like the English name of the enemy.
- This *doesn't* have the Freezard in various "broken" states like the MM64 object has.
Thus, I'm pretty sure these were named by Grezzo, and are *not* the original names of the MM64 assets.
Now to take a big sip of water and check how many objects start with  `object_g*`...
=> Add original asset names for all `object_e*` and `object_f*` files

include/z64save.h, src/code/z_demo.c, src/code/z_parameter.c, src/code/z_play.c, src/overlays/actors/ovl_En_Light/z_en_light.c, src/overlays/actors/ovl_En_Mag/z_en_mag.c, src/overlays/actors/ovl_En_Test4/z_en_test4.c, src/overlays/gamestates/ovl_daytelop/z_daytelop.c, src/overlays/gamestates/ovl_opening/z_opening.c, src/overlays/gamestates/ovl_title/z_title.c
`GAMEMODE_OWL_SAVE` is a new gamemode comparing to OoT and is set in z_message while processing the owl save. It can be seen here:
https://github.com/Decompollaborate/mm/blob/bd4086f0b80612e2f4c5ab4d58e4234ebcd8b4ee/src/code/z_message.c#L4885
Interestingly, `GAMEMODE_END_CREDITS` never seems to be set with the current decompiled code, although its usage is inferred from OoT (it's set in z_demo in OoT).
=> Introduce `SaveContext.gameMode` enum

Makefile
This flag makes the map file to actually have the static symbols and its corresponding addresses.
For example, having a `static` symbol like this:
```c
static struct_801F58B0 D_801F58B0[3][3];
```
Produces this in the map file
```
0x00000000801f58b0                build/src/code/z_player_lib.o:D_801F58B0
```
Which should allow us to have less problems with static bss symbols.
It works by prefixing the filename to the symbol name.
It also works with in-function-static symbols
=> Add  `--convert-statics=global-with-filename` flag to asm-processor

assets/xml/objects/object_boss03.xml, assets/xml/objects/object_boss07.xml, assets/xml/objects/object_boss_hakugin.xml
Tharo noticed on discord that some of the boss title cards were being extracted as I8 when they *should* be IA8, as per this displaylist:
```c
gDPLoadTextureBlock(OVERLAY_DISP++, (s32*)titleCtx->texture, G_IM_FMT_IA, G_IM_SIZ_8b, width, height, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMASK, G_TX_NOMASK, G_TX_NOLOD, G_TX_NOLOD);
```
I made sure all boss title cards were being extracted as IA8 here; if you don't see the title card in this PR, then it was *already* an IA8.
=> Ensure all boss title cards are extracted as IA8

src/code/z_room.c
Noticed a non-equivalency while testing NON_MATCHING builds. Fixed that and was able to finish off the function.
Note `ROOM_SHAPE_CULLABLE_MAX_ENTRIES` of 128 matches what is in the debug rom.
=> Match Room_DrawCullable

tools/fixbaserom.py
Adds an additional m5sum check of the compressed rom before trying to decompress in `fixbaserom.py`. Perhaps this makes the uncompressed md5sum check at the end unnecessary, but I decided to leave it anyways because 🤷.
=> Add compressed md5sum check to fixbaserom

src/overlays/actors/ovl_En_Wiz/z_en_wiz.c
This documents the cause of this 11-year-old softlock that can happen with the Wizrobe in the Secret Shrine: https://www.youtube.com/watch?v=pLudl60Rmz0
Thanks to Kaztalek for helping me investigate this one.
=> Document a bug involving quick-killing the Wizrobe

src/code/z_collision_check.c, src/code/z_play.c, tools/disasm/disasm.py, tools/disasm/variables.txt
This adds a couple of disasm hacks to 1 fix up the collision check bss for non-matchings, and 2 remove a fake symbol from play.
Main motivation was to fix up the collision check bss, as when building with NON_MATCHING it would error out the first time due to duplicate bss symbols from the in static function ones. Since I needed to add a hack for that, I thought I would just add one to remove the fake symbol from play, rather than wait for the function to be matched.
=> Add a Couple Disasm Hacks (Fix NON_MATCHING Builds)

src/code/z_actor.c, src/overlays/actors/ovl_En_Gb2/z_en_gb2.c, src/overlays/actors/ovl_En_Jgame_Tsn/z_en_jgame_tsn.c, src/overlays/actors/ovl_En_Rz/z_en_rz.c, src/overlays/actors/ovl_En_Zob/z_en_zob.c, src/overlays/actors/ovl_En_Zod/z_en_zod.c, src/overlays/actors/ovl_En_Zos/z_en_zos.c
I went through `functions.h` and looked at all functions that had `seqId` has a parameter. Then, I looked at callers to these functions to make sure they weren't using raw integers. I only found four, but the one in EnAob01 is already covered in #1234, so I just left it alone.
=> Use proper sequence names in certain actors

include/z64.h, src/boot_O2/sleep.c, src/overlays/actors/ovl_En_Al/z_en_al.c, src/overlays/actors/ovl_En_Encount1/z_en_encount1.c, src/overlays/actors/ovl_En_Encount1/z_en_encount1.h, src/overlays/actors/ovl_En_In/z_en_in.c, src/overlays/actors/ovl_En_Kusa2/z_en_kusa2.c, src/overlays/actors/ovl_En_Mushi2/z_en_mushi2.c, src/overlays/actors/ovl_En_Time_Tag/z_en_time_tag.c, src/overlays/actors/ovl_En_Tru/z_en_tru.c, src/overlays/actors/ovl_En_Tsn/z_en_tsn.c, src/overlays/actors/ovl_En_Zos/z_en_zos.c, src/overlays/actors/ovl_Obj_Chan/z_obj_chan.c, src/overlays/actors/ovl_Obj_Dhouse/z_obj_dhouse.c, src/overlays/actors/ovl_Obj_Fireshield/z_obj_fireshield.c, src/overlays/actors/ovl_Obj_Flowerpot/z_obj_flowerpot.c, src/overlays/actors/ovl_Obj_Grass_Carry/z_obj_grass_carry.c, src/overlays/actors/ovl_Obj_Iceblock/z_obj_iceblock.c, src/overlays/actors/ovl_Obj_Tokei_Step/z_obj_tokei_step.c
Small misc cleanup, mostly focused on converting instances of `this2` to `thisx` or something similar.
In this PR:
* remove this2's
* Use of exchangeItemId enums
* small clean up of Sleep_Cycles
* add ENENCOUT1_PATH_INDEX_NONE (which I messed up during a merge conflict)
* Capitalize `F` in `fram` enums for PascalCase.
=> Misc cleanup

src/overlays/actors/ovl_En_Racedog/z_en_racedog.c
Zoey brought this up in Discord a long time ago, but I never got around to actually updating the repo with an explanation: https://discord.com/channels/688807550715560050/688851976746041391/1010603501681905756
This explains how a dog can, with insanely precise positioning, finish the race "early", as showcased in this clip: https://clips.twitch.tv/CalmKnottyJackalUncleNox-paCX0rRveiM6-3mi
I also added some diagrams to this function to explain it better, because I think it's kind of hard to understand without just visually drawing it out. Let me know what you think about them.
=> Document a bug in EnRacedog and add some diagrams to EnRacedog_IsOverFinishLine

include/gfx.h
The comments for the offsets and size for `GraphicsContext` where wrong/shifted after `OSScTask`.
I also verified the offsets using offsetof/sizeof with custom osSyncPrintf calls inside an actor.
=> fix: wrong offset-comments in GraphicsContext

src/code/game.c, src/overlays/actors/ovl_Bg_Hakugin_Bombwall/z_bg_hakugin_bombwall.c, src/overlays/actors/ovl_En_In/z_en_in.c, src/overlays/actors/ovl_En_Minislime/z_en_minislime.c, src/overlays/actors/ovl_En_Railgibud/z_en_railgibud.c, src/overlays/actors/ovl_En_Talk_Gibud/z_en_talk_gibud.c, src/overlays/actors/ovl_En_Zot/z_en_zot.c, src/overlays/actors/ovl_Obj_Raillift/z_obj_raillift.c, src/overlays/actors/ovl_player_actor/z_player.c
Does some clean up regarding `requiredScopeTemp`s by converting them to actual used variables where appropriate, or in 1 case changing scope so it was no longer needed.
=> RequiredScopeTemp Cleanup

assets/xml/objects/object_ge1.xml, assets/xml/objects/object_geldb.xml, assets/xml/objects/object_gg.xml, assets/xml/objects/object_ghaka.xml, assets/xml/objects/object_gk.xml, assets/xml/objects/object_gla.xml, assets/xml/objects/object_goroiwa.xml, assets/xml/objects/object_goronswitch.xml
I was waiting for #1072 to be merged before starting this, but at this point it has a lot of conflicts, so what's one more?
This adds the original names from MM3D for objects that start with `object_g*`. Do note that I skipped all the GI objects, since I firmly believe that those are original Grezzo names, so I don't think they're very useful. I also skipped `object_gm` (because it's empty) and `object_gs` (because, like the GI objects, it seems to have been completely redone by Grezzo and named with their own naming scheme). Thus, this is a pretty small list of changes.
=> Add original asset names to all `object_g*` files

assets/xml/interface/schedule_static.xml, src/code/z_play_hireso.c
To be perfectly honest, I actually did not notice the unaccounted data in schedule_static when I PRd it with the bombers notebook. This finishes that off. 
~~So there is only one instance of unaccounted for data. It is just all 0xFF and lives between `gBombersNotebookLineTex` and `gBombersNotebookBarTex`, it is possible it was just another copy of `gBombersNotebookBarTex` just smaller but 🤷. I don't think it was a part of the line texture which is the only other option.~~
Decided to just go with a new small bar texture as that seems the most likely imo.
=> schedule_static docs

assets/xml/objects/object_ha.xml, assets/xml/objects/object_haka_obj.xml, assets/xml/objects/object_hakaisi.xml, assets/xml/objects/object_hakugin_demo.xml, assets/xml/objects/object_hakugin_obj.xml, assets/xml/objects/object_hana.xml, assets/xml/objects/object_harfgibud.xml, assets/xml/objects/object_hariko.xml, assets/xml/objects/object_hata.xml, assets/xml/objects/object_hgdoor.xml, assets/xml/objects/object_hintnuts.xml, assets/xml/objects/object_horse_game_check.xml, assets/xml/objects/object_horse_link_child.xml, assets/xml/objects/object_hs.xml, assets/xml/objects/object_hsstump.xml, assets/xml/objects/object_hunsui.xml
The most interesting (and potentially controversial) one of these in `object_hunsui`. In MM3D, they actually included some original N64 assets in the object:
The one actually used by MM3D stuck a "20" in the name like so:
But that raises some questions. Did the original N64 one have "20" in the name? If it did, why is there a collision file *without* "20" in the name? And speaking of collision, one of the collision files in MM64 is an unused duplicate. MM3D has two collision files...that are *also* duplicates. I just named the collision files after the DLs they are near, since that made the most sense, but perhaps we don't want to name either of them, given that we can't really know how the MM3D ones are supposed to map to the N64 ones since they're both duplicates.
=> Add original asset names to all `object_h*` files

Makefile
Adds a toggle to force the asm processor to process a file, which is very beneficial for bss reordering issues. Note the asm_processor chokes on files with statics that share the same name in the same file.
=> ASM_PROC_FORCE

src/overlays/actors/ovl_Bg_Numa_Hana/z_bg_numa_hana.c, src/overlays/actors/ovl_Bg_Numa_Hana/z_bg_numa_hana.h, src/overlays/actors/ovl_En_Grasshopper/z_en_grasshopper.c, src/overlays/actors/ovl_En_Grasshopper/z_en_grasshopper.h, src/overlays/actors/ovl_En_Pp/z_en_pp.c, src/overlays/actors/ovl_En_Pp/z_en_pp.h, src/overlays/actors/ovl_En_Rd/z_en_rd.c, src/overlays/actors/ovl_En_Rd/z_en_rd.h, src/overlays/actors/ovl_En_Snowman/z_en_snowman.c, src/overlays/actors/ovl_En_Tanron5/z_en_tanron5.c, src/overlays/actors/ovl_En_Tanron5/z_en_tanron5.h, src/overlays/actors/ovl_En_Wiz/z_en_wiz.c, src/overlays/actors/ovl_En_Wiz/z_en_wiz.h, src/overlays/actors/ovl_Obj_Tokeidai/z_obj_tokeidai.c, src/overlays/actors/ovl_Obj_Tokeidai/z_obj_tokeidai.h
In #1319, someone noted that "angular velocity" is the correct term for what I was calling "rotational velocity". However, the whole codebase was using "rotational velocity", so I said I'd stick with it for that PR and then fix it once the PR got merged. I then proceeded to forget about that until just now.
Besides changing "rotational velocity" to "angular velocity", this PR also cleans up some rotation names in BgNumaHana, since they were a bit weird.
=> Change all uses of "rotational velocity" to "angular velocity"

src/overlays/actors/ovl_Demo_Tre_Lgt/z_demo_tre_lgt.c
Noticed this while working on ZAPD, this array uses the old ``TransformUpdateIndex`` instead of ``CurveAnimationHeader``
=> Removed ``TransformUpdateIndex`` in z_demo_tre_lgt.c

assets/xml/objects/object_az.xml, assets/xml/objects/object_boss03.xml, assets/xml/objects/object_boss07.xml, assets/xml/objects/object_dblue_object.xml, assets/xml/objects/object_dog.xml, assets/xml/objects/object_f52_obj.xml, assets/xml/objects/object_ka.xml, assets/xml/objects/object_kaizoku_obj.xml, assets/xml/objects/object_kamejima.xml, assets/xml/objects/object_kanban.xml, assets/xml/objects/object_kbt.xml, assets/xml/objects/object_keikoku_demo.xml, assets/xml/objects/object_keikoku_obj.xml, assets/xml/objects/object_kepn_koya.xml, assets/xml/objects/object_kgy.xml, assets/xml/objects/object_kibako.xml, assets/xml/objects/object_kibako2.xml, assets/xml/objects/object_kin2_obj.xml, assets/xml/objects/object_kinsta1_obj.xml, assets/xml/objects/object_kinsta2_obj.xml, assets/xml/objects/object_kitan.xml, assets/xml/objects/object_knight.xml, assets/xml/objects/object_kumo30.xml, assets/xml/objects/object_kusa.xml, assets/xml/objects/object_kz.xml, assets/xml/objects/object_kzsaku.xml, assets/xml/objects/object_shn.xml, src/overlays/actors/ovl_Dm_Opstage/z_dm_opstage.c
Some notes:
- In `object_kamejima`, there's a third, unused piece of collision. MM3D *also* has three collision files, and while two of them map to the two used files exactly as expected, this third one doesn't really line up. However, I put in there that it may *possibly* be named after that third file in MM3D, but it's definitely shaky; I'm fine with removing this.
- While I was in `object_keikoku_demo`, I changed one instance of `ColliderHeader` to `Col`.
- In `object_kin2_obj`, I changed some whitespace to make some empty DLs more closely match the non-empty DL they are associated with.
- In `object_knight`, the animation names in MM3D are a bit weird; see the comment at the top of the file for more information.
- I didn't put any names for `object_kujiya`, because that object is done …
=> Add original asset names to all `object_k*` files

include/z64player.h, src/code/z_player_lib.c, src/overlays/actors/ovl_Boss_03/z_boss_03.c, src/overlays/actors/ovl_Door_Ana/z_door_ana.c, src/overlays/actors/ovl_En_Bigokuta/z_en_bigokuta.c, src/overlays/actors/ovl_En_Bigslime/z_en_bigslime.c, src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.c, src/overlays/actors/ovl_En_Dragon/z_en_dragon.c, src/overlays/actors/ovl_En_Raf/z_en_raf.c, src/overlays/actors/ovl_En_Railgibud/z_en_railgibud.c, src/overlays/actors/ovl_En_Rd/z_en_rd.c, src/overlays/actors/ovl_En_Rr/z_en_rr.c, src/overlays/actors/ovl_En_Talk_Gibud/z_en_talk_gibud.c, src/overlays/actors/ovl_En_Toto/z_en_toto.c, src/overlays/actors/ovl_En_Wiz_Fire/z_en_wiz_fire.c, src/overlays/actors/ovl_player_actor/z_player.c, tools/namefixer.py
Taken from Fig/OoT's PR here: https://github.com/zeldaret/oot/pull/1538, which has a good description of these variables.
This is a variable that changes purposes based on what player action is currently running (there are a lot of player actions so a lot of different uses for this). Anytime the player action changes, this variable is reset to 0 so that no previous action influences its value and it can start its new purpose.
=> Name player's generic `actionVar`s

assets/xml/objects/gameplay_keep.xml, assets/xml/objects/object_ladder.xml, assets/xml/objects/object_last_obj.xml, assets/xml/objects/object_lastday.xml, assets/xml/objects/object_lbfshot.xml, assets/xml/objects/object_lightblock.xml, assets/xml/objects/object_lightswitch.xml, assets/xml/objects/object_link_goron.xml, assets/xml/objects/object_link_zora.xml, assets/xml/objects/object_lotus.xml, assets/xml/objects/object_mamenoki.xml, assets/xml/objects/object_maruta.xml, assets/xml/objects/object_mastergolon.xml, assets/xml/objects/object_masterzoora.xml, assets/xml/objects/object_milkbar.xml, assets/xml/objects/object_mir_ray.xml, assets/xml/objects/object_mk.xml, assets/xml/objects/object_mm.xml, assets/xml/objects/object_mnk.xml, assets/xml/objects/object_moonend.xml, assets/xml/objects/object_moonston.xml, assets/xml/objects/object_ms.xml, assets/xml/objects/object_mu.xml, assets/xml/overlays/ovl_En_Mm2.xml
Some notes on this one:
- Most of the DLs in the various `object_link_*` objects got combined into the skeletal mesh, so we unfortunately can't get names for them:
- All the `object_mask*` stuff got moved to `zelda2_keep`, and similar to the `object_gi*` models, I'm fairly sure Grezzo just named these themselves, so I omitted them.
- `object_mbar_obj` and `object_meganeana_obj` got completely hollowed-out in MM3D, so we don't get names for those.
- For `object_mnk`, the rope that ties the monkey to the pole and the rope winch that holds him above the pot are actually skeletons with animations. These animations are all named in MM3D, but I don't think any human can realistically look at them and line them up visually with the animations in MM64. However, in EnMnk itself, there are arrays …
=> Add original asset names to all `object_l*` and `object_m*` files

assets/xml/objects/object_jso.xml
I had already done this in my branch that matches the `EnJso` actor, but I figured I should PR it separately to slim down the eventual PR for that actor. Most of these names I'm pretty confident in bar this limb:
I call it "RobeTop", since it goes above the top of the Garo's head. There are narrow bits that go all the way down the robe, but the more important thing is that this is where the top of the robe comes from. I didn't call it "hood" because Garo Master has this same limb, and it's not really a hood on him. I'm open to suggestions, though.
=> Document `object_jso` (Garo and Garo Master)

include/z64camera.h, src/code/z_camera.c
Turns out there were a lot of similarities between `Camera_KeepOn1` and `Camera_Battle1` (since they both related to targeting), so the tricks that worked for `Camera_Battle1` worked for `Camera_KeepOn1` as well.
Was honestly expecting these 3 camera functions to be the last 3 functions into 100%, I'm really shocked at these matches
=> Match `Camera_KeepOn1`

assets/xml/objects/object_nb.xml, assets/xml/objects/object_niw.xml, assets/xml/objects/object_nnh.xml, assets/xml/objects/object_numa_obj.xml, assets/xml/objects/object_ny.xml, assets/xml/objects/object_oF1d_map.xml, assets/xml/objects/object_ob.xml, assets/xml/objects/object_obj_chan.xml, assets/xml/objects/object_obj_danpeilift.xml, assets/xml/objects/object_obj_dinner.xml, assets/xml/objects/object_obj_milk_bin.xml, assets/xml/objects/object_obj_tokeidai.xml, assets/xml/objects/object_obj_usiyane.xml, assets/xml/objects/object_obj_yasi.xml, assets/xml/objects/object_omoya_obj.xml, assets/xml/objects/object_open_obj.xml, assets/xml/objects/object_ot.xml, assets/xml/objects/object_owl.xml, assets/xml/objects/object_oyu.xml
I should note that I skipped `object_os_anime` in this one. This is because this object isn't in the 3DS games; the animations were moved to the constituent objects. This is why `object_os_anime` has some `Cne_*` animations labelled right now; because I could get them from `zelda_cne`. However, I didn't want to bother with trying to chase down where any other animations came from until OoT's EnHy was documented.
=> Add original asset names to all `object_n*` and `object_o*` files

src/code/z_message.c
This was likely one of those `!gSaveContext.prevHudVisibility` instead of just doing `gSaveContext.prevHudVisibility == 0` where `0` is the enum value `HUD_VISIBILITY_IDLE`
=> Match `Message_Update`

src/code/z_demo.c
On gcc with strict-aliasing on (as is default) this could cause improper codegen sometimes due to breaking strict-aliasing rules. This fixes the issue and maintains matching.
Oddly, gcc seems to have trouble identifying when it should warn about strict-aliasing related issues, as this did not cause a warning.
=> Fix aliasing in Cutscene_SetActorCue

assets/xml/objects/gameplay_field_keep.xml, assets/xml/objects/gameplay_keep.xml, assets/xml/objects/object_hana.xml, assets/xml/objects/object_moonend.xml, assets/xml/objects/object_ssh.xml, assets/xml/objects/object_syokudai.xml, assets/xml/objects/object_syoten.xml, assets/xml/objects/object_wood02.xml, assets/xml/objects/object_zog.xml, assets/xml/overlays/ovl_Obj_Grass.xml, assets/xml/overlays/ovl_Obj_Jgame_Light.xml
Fixes most assets from using hardcoded pointers.
Many of the issues were caused by blobs being too big so ZAPD couldn't create the corresponding symbol automatically. Some others where gameplay_keep symbols not present in the xml, so ZAPD couldn't see them when crossreferencing.
The remaining hardcoded symbols are the ones from Z2_SEA (Great Bay Temple) which are handled by `Scene_DrawConfigGreatBayTemple` and a few limbs from object_osn and object_dmask that reference dlists from gameplay keep but for some ZAPD doesn't symbolize them
=> Fix most hardcoded pointers in extracted assets

include/z64player.h, src/overlays/actors/ovl_player_actor/z_player.c
Similar to this PR: https://github.com/zeldaret/oot/pull/1446
Based on the names of animations in D_8085BE84 for each PLAYER_ANIMGROUP_, I updated the names of PLAYER_ANIMGROUP_ values.
Of course this is meant to be temporary, as noted in a comment above the enum definition
I think keeping the lowercase is good because it avoids interpretation of the original names, and it makes it look temporary
=> Player doc: Temporary `PLAYER_ANIMGROUP` names from original animation names

assets/xml/archives/icon_item_static.xml
The offsets for gItemIconLandDeedTex and gItemIconMoonsTearTex in icon_item_static.xml were switched. I have switched them to 0x28000 and 0x29000 respectively.
=> Switch icon_item_static.xml offset addresses

Makefile
Bring over OOT's makefile section to allow changing the default mips tool chain.
=> Allow the mips tool chain to be picked via command argument

Jenkinsfile, tools/Makefile
Jenkins updated and it now requires to use a venv to install Python packages.
Also, building z64compress on the new Jenkins produce a warning about `-flto`, which produces the CI to fail. As a workaround I'm overriding its CFLAGS on the tools makefile
https://stackoverflow.com/questions/72218980/gcc-v12-1-warning-about-serial-compilation
=> Add venv to Jenkins

requirements.txt, tools/disasm/disasm.py
The latest version of `rabbitizer` (1.9.1) performs a few runtime checks to prevent the user from doing the wrong thing, which just bite us and showed a bug on our usage of `rabbitizer`.
The bug was caused because we were trying to check if the processed instruction was the jump kind of instruction but it has the target address embedded in the instruction itself (like `jal` and `j`), but the code was checking for every kind of jump, including the ones that use a register to jump to (like `jalr` and `jr`), meaning we were sometimes reading garbage :sweat_smile: .
I bumped the required rabbitizer version to the version that introduces the new function I'm using instead of the latest one.
=> Fix disasm.py

src/overlays/actors/ovl_Bg_Hakugin_Post/z_bg_hakugin_post.c
`unkStruct->unk_0000` is an array of `BgHakuginPostUnkStruct1` and this copy call is copying one entry to another index, so the hardcoded size can be switched to a `sizeof(BgHakuginPostUnkStruct1)` to better represent that.
=> bg_hakugin_post: replace hardcoded size for sizeof

src/overlays/actors/ovl_Bg_Breakwall/z_bg_breakwall.c
This fixes an incorrect DL reference for the great bay storm effect. `func_808B7B54` renders two separate "storm" effects. One of the DL calls goes to `object_posthouse_obj_DL_000A50`, but that is the postmans backpack and hat in the post office. The correct DL for the storm should be `object_kumo30_DL_000A50`.
I presume since both `object_posthouse_obj_DL_000A50` and `object_kumo30_DL_000A50` have the same offset of `0xA50` and objects are loaded into segment 6, that that is why both are considered matching.
=> bg_breakwall: fix great bay storm dl reference

Jenkinsfile
Missed installing GitPython in the new `venv` environment for running the progress script for Jenkins
=> Jenkinsfile Hotfix: install GitPython for progress script

docs/tutorial/vscode.md
JSON does not like trailing comma on arrays.
=> Remove tailing comma from vscode json file

assets/xml/objects/object_sb.xml, assets/xml/objects/object_sdn.xml, assets/xml/objects/object_secom_obj.xml, assets/xml/objects/object_sek.xml, assets/xml/objects/object_sichitai_obj.xml, assets/xml/objects/object_sinkai_kabe.xml, assets/xml/objects/object_skb.xml, assets/xml/objects/object_slime.xml, assets/xml/objects/object_smtower.xml, assets/xml/objects/object_snowwd.xml, assets/xml/objects/object_spdweb.xml, assets/xml/objects/object_spidertent.xml, assets/xml/objects/object_spinyroll.xml, assets/xml/objects/object_spot11_obj.xml, assets/xml/objects/object_ssh.xml, assets/xml/objects/object_st.xml, assets/xml/objects/object_syokudai.xml, assets/xml/objects/object_syoten.xml
A couple of notes:
- MM3D removed `object_sth`, `object_stream`, and all of the `object_sekihi*` objects. The first was just `object_boj` with the animations removed, and the second was the object used for an unused actor. However, while most of the `sekihi` objects were unused grave variations, `object_sekihiz` *was* used for the Song of Soaring pedestal in MM64. How did they handle that pedestal in MM3D? They simply baked it into the Southern Swamp scene.
- The original skulltula token assets from MM64 are actually in MM3D's version of `object_st`. This isn't exactly noteworthy by itself, but it explicitly confirms that the `_model` DList comes before the `_modelT` DList, which is extremely rare.
- Speaking of Skulltulas, the unused animation in `object_sth` is clearly intended to be a …
=> Add original asset names to all `object_s*` files

src/code/z_parameter.c
Examples of what the ammo count looks like with each of the wallet tiers:
=> Document missing gDPSetEnvColor

src/code/z_eff_blure.c, src/overlays/actors/ovl_En_Mnk/z_en_mnk.c, src/overlays/actors/ovl_En_Osn/z_en_osn.c
After seeing the bug about early returns in a OPEN/CLOSE_DISPS pairs, I did some poking around and found some areas that I think can be improved.
* Happy Mask Salesman draw had a misplaced `CLOSE_DISPS`. Originally this matched for retail, but I imagine would fail for debug rom matching (when CLOSE_DISPS becomes more than a closing bracket)
* The Monkey face draw had some returns in a switch, but reworking this to move the one `gSPSegment` up into the `default` case means we can swap the `return` for `break` in the other cases and still be matching
* The last one I found was in `eff_blure` where there are returns for null mtx or no elements to draw. ~~Here I opted for `goto close_disps` which sorta matches other places that this is done (`z_eff_spark`, `z_skin`)~~ Instead, per feedback …
=> CLOSE_DISPS fixes and avoid early return

src/overlays/actors/ovl_En_Toto/z_en_toto.c
IDO will never reorder these arrays but some compilers will depending on optimization settings. This causes a problem when a sub array is indexed or the pointer is incremented more than the capacity of the sub array.
=> Consolidate text array

assets/xml/overlays/ovl_Oceff_Wipe.xml
The song of time frustum vtx count in the xml did not match the actual size used by the code.
https://github.com/zeldaret/mm/blob/7a26cca36d87d228909c9ecda0dc3403f2b150df/src/overlays/actors/ovl_Oceff_Wipe/z_oceff_wipe.c#L94-L98
Here the loop happens 20 times, with `i` being multiplied by 2 for a total of 40 vtx.
This aligns with an additional 8 vtx being extracted unnamed.
=> Fix Song of Time frustum Vtx count

src/overlays/actors/ovl_player_actor/z_player.c
This last function in z_player seems to be responsible for setting the players animation during dialogue sequences. There are times where the passed in `talkAnim` will be `NULL`.
There is a ternary on `talkAnim` to use an alternate animation provided by `func_8082ED20` (which chooses a default wait animation based on the players form/current mask), but this only happens for one of the arguments to `PlayerAnimation_Change`. `Animation_GetLastFrame` in this case will still get `NULL` passed into it, which internally is fed into `Lib_SegmentedToVirtual`. This leads to `Animation_GetLastFrame` returning a value of `15385`.
I can't seem to discern a difference between the real last frame value being passed in vs this large value, so I didn't elect to document the result of it.
I also tried to …
=> Document bug in talk wait animation frame count

src/overlays/actors/ovl_En_Fish2/z_en_fish2.c
This array, like the one in en_toto, needs to be consolidated. When the fish is at its largest size it will overflow the first array with index 5. When combined, the game would read into the second array. We can only rely on this behavior with IDO since gcc may reorder arrays that are static regardless of flags.
=> Consolidate array | z_en_fish2

src/overlays/actors/ovl_En_Mt_tag/z_en_mt_tag.c
Not sure what the extent of the bug causes but surprised it doesn't cause crashes since from my understanding, the upper limit of the loop should be 3268542464 for sceneExitIndex 18.
=> Document Bug in EnMttag_GetCurrentCheckpoint and Cleanup

src/overlays/actors/ovl_En_S_Goro/z_en_s_goro.c
This code
```c
if ((s32)this != -0x190) {
```
Was actually a `NULL` check for the member at offset `0x190`, in this case `collider`. The only way for `&this->collider` could be `NULL` is that `this` has value `-0x190`.
Shoutouts to @cadmic for figuring this out for an AF scratch.
Convo: https://discord.com/channels/688807550715560050/1139317895491506197/1240420736095490239
=> Fix a fake match on `EnSGoro`

include/z64actor.h, src/code/z_actor.c, src/overlays/actors/ovl_En_Test2/z_en_test2.c
I believe these should be the other way around based on the comments. The checks in z_actor mean that it only skips drawing when in lens mode 0
=> Fix LensMode Names

Makefile, include/PR/gbi.h, src/code/sys_math3d.c, src/code/z_bgcheck.c, src/code/z_lights.c, src/code/z_map_disp.c, src/code/z_message.c, src/overlays/actors/ovl_Dm_Char00/z_dm_char00.c, src/overlays/actors/ovl_Dm_Char04/z_dm_char04.c, src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c, src/overlays/actors/ovl_En_Invadepoh_Demo/z_en_invadepoh_demo.c, src/overlays/actors/ovl_En_Kusa2/z_en_kusa2.c, src/overlays/actors/ovl_En_Osk/z_en_osk.c, src/overlays/actors/ovl_En_Ot/z_en_ot.c, src/overlays/actors/ovl_En_Zoraegg/z_en_zoraegg.c, src/overlays/actors/ovl_Obj_Flowerpot/z_obj_flowerpot.c, tools/calc_bss.sh
This PR syncs gbi.h with OoT, except for the addition of the custom macro `gDPSetdither` and moving the ucode defines into the makefile rather than setting them at the top of the header.
Also corrects usage of `gDPSetDither`.
This will exactly match OoT's gbi.h once https://github.com/zeldaret/oot/pull/1968 is merged
=> Format gbi.h, move ucode defines to makefile

src/overlays/actors/ovl_En_S_Goro/z_en_s_goro.c
Uses `intptr_t` casts to suppress the address warning in `en_s_goro`. Very ugly, but seems the least of all the evils.
=> Suppress address warning in en_s_goro

assets/xml/objects/object_tab.xml, assets/xml/objects/object_taisou.xml, assets/xml/objects/object_takaraya_objects.xml, assets/xml/objects/object_tanron4.xml, assets/xml/objects/object_taru.xml, assets/xml/objects/object_tite.xml, assets/xml/objects/object_tk.xml, assets/xml/objects/object_tokei_step.xml, assets/xml/objects/object_tokei_tobira.xml, assets/xml/objects/object_tokei_turret.xml, assets/xml/objects/object_toryo.xml, assets/xml/objects/object_trap.xml, assets/xml/objects/object_tree.xml, assets/xml/objects/object_tro.xml, assets/xml/objects/object_trt.xml, assets/xml/objects/object_tru.xml, assets/xml/objects/object_tsn.xml, assets/xml/objects/object_tsubo.xml, assets/xml/objects/object_twig.xml, assets/xml/overlays/ovl_En_Tanron1.xml, assets/xml/overlays/ovl_Obj_Jgame_Light.xml
Some notes:
- For `object_tite`, there are 8 animation in MM64, but there are only 7 animations in MM3D. Two of the eight animations in MM64 are unused; of the unused ones, I thought the first one is probably the `tt_dmg` animation; it matches the MM3D motion a little better, and it makes sense with the way they typically alphabetize animations
- For `object_tk`, I figured I'd extract the blobs while I was in there. One of the blobs was *already* being extracted automatically by ZAPD; it was being extracted as a 40x1 TLUT, which I just preserved, though I didn't know if there was a more "correct" way of extracting it. The other blob looks like two textures; I gave them dimensions that make the textures make sense, though both textures are unused, so it's hard to figure out their purpose. …
=> Add original asset names to all `object_t*` files

Makefile
This PR adds Makefile machinery for building samples, laying the groundwork for building samplebanks and soundfonts. Note that samples are not yet built, as nothing currently depends on these rules. Using these rules will begin in the next PR where samplebanks will be built.
=> [Audio 3/?] Set up building samples

assets/xml/boot/fault_drawer.xml, src/boot/fault_drawer.c
This extracts sFaultDrawerFont as a blob using ZAPD (at least for a temporary stop gap for now). This allows removing the `GLOBAL_ASM` `#pragma` from `fault_drawer.c`.
=> Extract sFaultDrawerFont as blob

README.md, docs/CONTRIBUTING.md, docs/REVIEWING.md, docs/tutorial/introduction.md
Update link to use the new domain (only place zelda64.dev still exists is in the Jenkinsfile for the folder where we store progress files)
resolves #1689
=> Update website links

Makefile
Was starting to get some argument list too long errors again that would cause `make init` fail. Changes the mkdir commands slightly to help address this.
=> Divy out mkdir some more in the makefile

tools/audio/samplebank.c, tools/audio/samplebank_compiler.c, tools/audio/soundfont_compiler.c, tools/audio/xml.c
Mirror of https://github.com/zeldaret/oot/pull/2257
=> Add missing std headers to audio tools

.gitignore, tools/.gitignore, tools/buildtools/.gitignore
Cleans up some gitignore files.
Highly recommended to checkout the PR and see what it no longer ignores for you to see if we need to add something back.
=> Clean up gitignores

include/build.h, src/boot/CIC6105.c, src/boot/build.c
See here for the motivation of this rename:
https://github.com/zeldaret/oot/pull/2160
=> Rename gBuildTeam to gBuildCreator

docs/tutorial/vscode.md
Adds the extracted/n64-us include directory to the vscode doc (forgot to do it with the extracted PR).
=> Update vscode doc

src/code/z_message.c
When playing the zora guitar jam session with Japas, this expression would eval as `1 << (18 + 65)` leading to a left shift of 83, which is UB for u32. Rewriting this to use enums for `EVAN_PART` and matching the surround expressions for `AudioOcarina_Start` produces a matching rom without UB.
The new expression will eval as `1 << ((65 - 65) + 19)` leading to a left shift of 19. I'm guessing the previous shift of 83 was rolling over twice (`83-32-32 == 19`)
=> Fix ocarina start UB for Japas jam session

assets/xml/objects/object_yado_obj.xml, assets/xml/objects/object_yb.xml, assets/xml/objects/object_yukimura_obj.xml, assets/xml/objects/object_yukiyama.xml, assets/xml/objects/object_zg.xml, assets/xml/objects/object_zl1.xml, assets/xml/objects/object_zl4.xml, assets/xml/objects/object_zm.xml, assets/xml/objects/object_zo.xml, assets/xml/objects/object_zob.xml, assets/xml/objects/object_zod.xml, assets/xml/objects/object_zog.xml, assets/xml/objects/object_zoraband.xml, assets/xml/objects/object_zoraegg.xml, assets/xml/objects/object_zov.xml, src/overlays/actors/ovl_En_Yb/z_en_yb.c
This wraps up this type of work for every `object_*` file. There are still the assets in overlays and in the `*_keep` files remaining. Some notes on this PR:
- I saw a note in `object_yb` stating that a particular animation doesn't work in Z64Utils. This was a little strange to me, since it worked fine for me, so I just removed the comment. You can see it load just fine here:
- Similarly, there was a comment in `z_en_yb.c` saying that loading that animation in-game crashes. Again, this was strange to me, since it worked fine for me, so I again just removed the comment. I just changed `EnYb_ChangeAnim(play, this, 2, ANIMMODE_LOOP, 0.0f)` to `EnYb_ChangeAnim(play, this, 0, ANIMMODE_LOOP, 0.0f)` and it worked as expected. Here's a video of it in action: …
=> Add original asset names to all `object_y*` and `object_z*` files

assets/xml/overlays/ovl_Arrow_Fire.xml, assets/xml/overlays/ovl_Arrow_Ice.xml, assets/xml/overlays/ovl_Arrow_Light.xml, assets/xml/overlays/ovl_En_Bom.xml, assets/xml/overlays/ovl_En_Clear_Tag.xml, assets/xml/overlays/ovl_En_Gakufu.xml, assets/xml/overlays/ovl_En_Holl.xml, assets/xml/overlays/ovl_En_Horse_Game_Check.xml, assets/xml/overlays/ovl_En_Tru.xml, assets/xml/overlays/ovl_Oceff_Spot.xml, assets/xml/overlays/ovl_Oceff_Storm.xml, assets/xml/overlays/ovl_Oceff_Wipe.xml, assets/xml/overlays/ovl_Oceff_Wipe2.xml, assets/xml/overlays/ovl_Oceff_Wipe3.xml, assets/xml/overlays/ovl_Oceff_Wipe4.xml, assets/xml/overlays/ovl_Oceff_Wipe5.xml, assets/xml/overlays/ovl_Oceff_Wipe6.xml, assets/xml/overlays/ovl_Oceff_Wipe7.xml
A lot of these are "fuzzier" than the assets that were originally in object files; Grezzo tended to just shove a lot of this into `zelda2_keep.gar.lzs`, which is MM3D's equivalent of `gameplay_keep`, and it's a little less obvious if they kept the name while they were doing so or if they changed it. The Ocarina effects are a great example; in OoT3D, we can see that *every* Ocarina effect starts with `efc_ocarina_*`. In MM3D, they actually remade some of these assets, and in `zelda2_keep.gar.lzs`, they included both the OoT3D asset (as `efc_ocarina_*`) and the MM3D asset (as `ocarina_*_model`). So which one was originally used in MM? It's hard to say; I *suspect* it was `efc_ocarina_*`, since what reason would they have to change it for the reused effects? But that doesn't explain the Song …
=> Add original asset names to all assets present in overlays

assets/xml/objects/object_dmask.xml, assets/xml/objects/object_osn.xml
Skeletons in these objects have references to display lists in gameplay_keep, so they should rely on gameplay_keep as an ExternalFile.
Unfortunately though, adding these to the xmls do not appear to actually replace the hardcoded gameplay_keep pointers with symbols.. a ZAPD bug?
=> Add missing ExternalFile tags to object_dmask and object_osn

Makefile, include/variables.h, include/z64audio.h, spec, src/audio/lib/load.c, src/audio/session_config.c, src/audio/session_init.c
~~`gAudioHeapInitSizes` isn't really const since it is written to, but it seems necessary for matching. When `AVOID_UB` is defined, do not qualify `gAudioHeapInitSizes` with const so we can use a regular assignment where it is written to.~~
New strategy:
Split `gAudioTatumInit` and `gAudioHeapInitSizes` into `session_init.c`, which incrementally links .data into .rodata instead of using any const qualifiers.
=> Move gAudioTatumInit and gAudioHeapInitSizes to their own file, using data-with-rodata instead of const qualifiers

assets/xml/objects/gameplay_dangeon_keep.xml, assets/xml/objects/gameplay_field_keep.xml
This was pretty straightforward, though I did have to grab the original name of the rusted switch from OoT3D, since it's absent in MM3D. There are a couple of names that are in MM3D, but I don't know what the equivalent asset is in MM. There's a grass asset called `grass05_model`, but there are two grass assets in `gameplay_field_keep`; perhaps one of them is supposed to be opaque and one is supposed to be transparent like with the two rock assets? The crystal switch is also called `s2_OPAT_model`, but in MM3D, it's just all one asset, so I don't know which of the three DLs that might correspond to.
=> Add original asset names to `gameplay_field_keep` and `gameplay_dangeon_keep`

include/attributes.h, include/fault.h, include/functions.h, include/libu64/debug.h, src/boot/fault.c, src/boot/libu64/debug.c, src/code/code_80183070.c
Some rationale in the corresponding OoT PR
https://github.com/zeldaret/oot/pull/1532
=> Apply the NORETURN attribute to functions that do not return

include/z64bgcheck.h
I checked if the surface types elements are placed the same as OoT and it is afaict, note that there's minor inconsistencies (like the "wall damage" thing that is still named `unk27`), I wasn't really sure so I thought this could be solved during review (or in the future)
I placed the macros at the beginning of the file since this is where most macros are located in this file, let me know if I should move the waterbox and surface types ones around the corresponding structs like it is on OoT (though for the waterbox macros there was already one at the top of the file so that's basically the whole reason I did it that way)
=> Add the bgcheck macros from OoT

src/audio/lib/load.c, src/audio/voice_internal.c, src/code/z_parameter.c, src/overlays/actors/ovl_En_Test7/z_en_test7.c, src/overlays/actors/ovl_Obj_Um/z_obj_um.c, src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_map.c
Fixes some warnings from clang, as well as fix a few fake matches:
* ObjUm PostLimbDraw
* EnTest7_DrawFeathers
* EnTest7_UpdateFeathers
=> Misc Fixes

include/buffers.h, linker_scripts/final/undefined_syms.ld, src/code/sys_cfb.c
Allows for the removal of both `gFramebufferHiRes0` and `gFramebufferHiRes1`
=> Match SysCfb_Init without extra symbols

assets/xml/objects/gameplay_keep.xml
This PR might seem a bit redundant, since the player animations are currently named after their original names (if the original name is available). The reason I want to do this, however, is that player animation names are probably going to change in the future, and I want to preserve these original names in the comments. This might seem silly:
```xml
<PlayerAnimation Name="gPlayerAnim_link_keirei" Offset="0xD9F8" /> 
```
But it seems much more reasonable when the animation is renamed:
```xml
<PlayerAnimation Name="gPlayerSaluteAnim" Offset="0xD9F8" /> 
```
I've described the history of how I derived these original animation names in previous PRs, but to summarize, Grezzo included almost all of the original animation data (just converted to little endian) for OoT's animations in OoT3D; for …
=> Document original player animation names in `gameplay_keep`

Makefile
There are already makefile rules to build the other audio file types out of `assets/audio` instead of `extracted/$(VERSION)/assets/audio`, so these files should have the same treatment
=> Add makefile rule to build sample blobs out of assets/

include/z64player.h, src/boot/yaz0.c, src/code/z_message_nes.c, src/code/z_player_lib.c, src/overlays/actors/ovl_En_Dnq/z_en_dnq.c, src/overlays/actors/ovl_player_actor/z_player.c
Special thanks to @fig02 for the GCC playthrough that uncovered these, and for everyone else who looked into and discussed the problems.
The `z_message_nes.c` AVOID_UB is particularly nasty.. suggestions welcome
=> Provide AVOID_UB for some bugs found in GCC compiler testing

Dockerfile, Makefile, docs/BUILDING_DOCKER.md, tools/asm-processor/compile-test.sh, tools/calc_bss.sh, tools/check_format.sh, tools/reloc_spec_check.sh, tools/rename_sym.sh, tools/warnings_count/check_new_warnings.sh, tools/warnings_count/compare_warnings.sh, tools/warnings_count/update_current_warnings.sh
Bash is not guaranteed to be at `/bin/bash` so the build process fails on Linux distributions where this is not the case. This PR fixes that by replacing `/bin/bash` with `/usr/bin/env bash` which correctly resolves the path to bash.
=> Fix /bin/bash -> /usr/bin/env bash

Makefile, spec, src/gcc_fix/missing_gcc_functions.c, tools/buildtools/mkldscript.c
This PR adds support for building the project with a modern MIPS GCC compiler.
Thanks to @fig02 for testing a build on hardware, and everyone who engaged in related discussions.
=> GCC Compiler Support

Makefile, assets/audio/sequences/seq_0.prg.seq, assets/audio/sequences/seq_1.prg.seq, include/audio/aseq.h, src/audio/lib/seqplayer.c
Macroify the Music Macro Language (MML) opcodes, and use them in the sequence player interpreter.
Companion PR to https://github.com/zeldaret/oot/pull/2485
=> Macroify MML opcodes

src/code/z_parameter.c
In Interface_UpdateButtonsPart2, there is a bug causing empty C-buttons to be disabled inconsistently (for most forms, they are enabled, but when Deku Link, they are disabled): [Example](https://tcrf.net/The_Legend_of_Zelda:_Majora%27s_Mask/Program_Revision_Differences#C-Buttons)
This is because the function checks the 255th index of the second dimension of gPlayerFormItemRestrictions - a dimension which has only been allocated 114 elements. This leads to inconsistent behaviour.
=> Document inconsistent empty C-button disabling bug
