- include/functions.h
- src/boot_O2_g3/boot_0x800968B0.c
- tables/functions.txt
> Matched func_800968B1

- Makefile
Implemented by making disasm an intermediate target and having all assembly files need it as a prerequisite. Another option I considered was grouped explicit targets, a feature that allows one rule to generate multiple targets. However, this is a relatively new feature added in 4.3. At least with my Ubuntu installation, the package manager only has 4.2.1, so I did not think it was safe to assume that users would have this version of make.
A caveat of this change is that it also add disasm to most .c files, since some have non-matchings that depend on the split .asm to compile. Compilation could be speed up by only the .c files that need it to depend on disasm so that the others can be compiled while disassembling is occurring. Since disassembling does take all that long however, I choose …
> Make the disasm target when appropiate instead of needing to do it manually

- include/variables_overlay.h
- include/z64.h
- linker_scripts/code_script.txt
- src/overlays/actors/ovl_En_Torch/z_en_torch.c
- tables/variables.txt
I ran the format script and it made the init vars look really weird. Not sure if that's what we wanted, but that's what happened when I ran the script, so I left it
> en_torch OK

- Jenkinsfile
All building is now done on non-master agents and the progress information is stashed and then unstashed from master, which updates the public files.
> Jenkins update

- src/overlays/actors/ovl_Obj_Ending/z_obj_ending.c
- src/overlays/actors/ovl_Obj_Ending/z_obj_ending.h
C functions all match, but every time I try to bring the data into the c file the rom checksum fails.
> Ovl obj ending OK but no data

- linker_scripts/code_script.txt
- src/overlays/actors/ovl_Dm_Ravine/z_dm_ravine.c
- src/overlays/actors/ovl_Dm_Ravine/z_dm_ravine.h
- tables/functions.txt
Hey - this is my first contribution to this project, so I picked a pretty simple overlay to get started. 
- I got the name "Link Riding Through Lost Woods Cutscene - Tree Trunk" from https://wiki.cloudmodding.com/mm/File_List/USA_GC - but I'm not sure how to verify it, or if it's descriptive enough? (Should I just call it "Unknown" instead?)
- There's a bit more info about what `RoomContext.unk7A` could be - but I think it's better to leave it `unk` until it's used in a few more places? (Also the code in `z_room.c` seems to suggest it really is an array and not 3 separate fields?)
- The unused function `DmRavine.actionFunc` is a bit weird. I'm sort of guessing it's an "action function" based on some other overlays that put a fn pointer after the base `Actor` struct. (Maybe it should stay …
>  ovl_Dm_Ravine (Link Riding Through Lost Woods Cutscene - Tree Trunk)

- src/overlays/actors/ovl_En_Encount2/z_en_encount2.c
- src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
- tools/actorfixer.py
`actorfixer.py` is a small python script made to fix automatically problems produced by functions renames that could affect actors.
Currently, the only function it has is `Actor_GetSwitchFlag` -> `Flags_GetSwitch`
I suggest to everyone doing bigger function renames to add their renames to this script when PR their changes.
> Port `actorfixer.py` to MM

- tools/sort_actor_funcs.py
---
This script gathers neccessary forward-declare functions and also sorts extern symbols, printing them to the console.
> Sort actor functions and extern'd symbols

- tools/sfxconvert.py
---
This was a drop-in port. It seems to be working without any change.
> Port sfxconvert

- CONTRIBUTING.md
- README.md
> Updates README to add an FAQ, and also updates CONTRIBUTING to be explicit on the reservation workflow process.

- spec
- src/overlays/actors/ovl_Obj_Lightblock/z_obj_lightblock.c
- src/overlays/actors/ovl_Obj_Lightblock/z_obj_lightblock.h
> ovl_obj_lightblock OK

- src/libultra/io/epirawread.c
---
The offer to package these into more than one per PR is still on the table
> epirawread OK

- include/ultra64/hardware.h
- src/libultra/io/epirawdma.c
- src/libultra/io/epirawwrite.c
---
Bout to have a whole page of PRs to myself
> epirawdma OK

- include/io/controller.h
- src/libultra/io/contquery.c
- src/libultra/io/contreaddata.c
- src/libultra/io/controller.c
- src/libultra/io/contsetch.c
- src/libultra/io/motor.c
- src/libultra/io/pfsisplug.c
- src/libultra/voice/voicegetstatus.c
- tools/disasm/variables.txt
---
This one has some variable renames. That should be it for all the pfs stuff, I think.
> pfsisplug OK

- src/libultra/io/pfsselectbank.c
---
Not a lot going on here. The most interesting question seems to be what order to put the headers in.
> pfsselectbank OK

- spec
- src/overlays/actors/ovl_Obj_Yado/z_obj_yado.c
- src/overlays/actors/ovl_Obj_Yado/z_obj_yado.h
> ovl_Obj_Yado ok

- tools/actorfixer.py
> Fix actorfixer

- spec
- src/overlays/actors/ovl_Obj_Dowsing/z_obj_dowsing.c
- src/overlays/actors/ovl_Obj_Dowsing/z_obj_dowsing.h
> ovl_Obj_Dowsing ok

- spec
- src/overlays/actors/ovl_Obj_Jg_Gakki/z_obj_jg_gakki.c
- src/overlays/actors/ovl_Obj_Jg_Gakki/z_obj_jg_gakki.h
---
adding the small gakki actor decompilation. all tests passing, happy for feedback on missed variables etc.
> Ovl obj jg gakki

- src/overlays/actors/ovl_En_Ginko_Man/z_en_ginko_man.c
> Update and fix a few comments for the banker.

- assets/xml/objects/object_cow.xml
- src/overlays/actors/ovl_En_Cow/z_en_cow.c
- src/overlays/actors/ovl_En_Cow/z_en_cow.h
- src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c
---
I was originally planning on doing this for the object documentation tutorial, but after doing object_dns, I realized that I already wrote tons of text, and people probably wouldn't read it. So instead, I'm just documenting it as a separate PR. While this object is a complete duplicate of what's in OoT, I did clean it up a bit; if these changes get approved, I'll backport them …
> Document object_cow

- tools/actorfixer.py
> Add missing actorfixer stuff

- Jenkinsfile
- src/overlays/actors/ovl_En_Firefly/z_en_firefly.c
> Set up AnsiColor Jenkins plugin

- spec
- src/overlays/actors/ovl_En_Fishing/z_en_fishing.c
---
I've long known that these two non-matchings were variable scoping issues, but I've been too scared of the stack problems to actually do them until now. Big shoutouts to Anon58 for helping me wrap up EnFishing_UpdateFish.
~~The remaining non-matching is EnFishing_UpdateLure: https://decomp.me/scratch/TS7zq~~
Thanks to @Synray, EnFishing_UpdateLure is now matching, so En_Fishing …
> En_Fishing OK (three functions matched)

- assets/xml/objects/object_aob.xml
- src/code/z_en_hy_code.c
- src/overlays/actors/ovl_En_Aob_01/z_en_aob_01.c
- src/overlays/actors/ovl_En_Aob_01/z_en_aob_01.h
---
Frankly, this object was a bit stranger than I was expecting. But overall, it wasn't super complicated.
> Document object_aob (Mamamu Yan's object)

- spec
- src/overlays/actors/ovl_Obj_Hamishi/z_obj_hamishi.c
- src/overlays/actors/ovl_Obj_Hamishi/z_obj_hamishi.h
> Obj_Hamishi

- tools/ZAPD/.gitrepo
- tools/ZAPD/ExporterTest/CollisionExporter.cpp
- tools/ZAPD/ExporterTest/ExporterTest.vcxproj
- tools/ZAPD/ZAPD/ZAPD.vcxproj
- tools/ZAPD/ZAPD/ZAPD.vcxproj.filters
- tools/ZAPD/ZAPD/ZArray.cpp
- tools/ZAPD/ZAPD/ZCollision.cpp
- tools/ZAPD/ZAPD/ZCollision.h
- tools/ZAPD/ZAPD/ZCollisionPoly.cpp
- tools/ZAPD/ZAPD/ZCollisionPoly.h
- tools/ZAPD/ZAPD/ZResource.cpp
- tools/ZAPD/ZAPD/ZResource.h
- tools/ZAPD/ZAPDUtils/Utils/BitConverter.h
- tools/ZAPD/ZAPDUtils/ZAPDUtils.vcxproj
subrepo:
subdir:   "tools/ZAPD"
merged:   "87cb648b"
upstream:
origin:   "https://github.com/zeldaret/ZAPD.git"
branch:   "master"
commit:   "87cb648b"
git-subrepo:
version:  "0.4.3"
origin:   "???"
commit:   "???"
---
> ZAPD update

- assets/xml/interface/do_action_static.xml
- assets/xml/interface/week_static.xml
- assets/xml/misc/story_static.xml
- spec
---
Also included is a bit of cleanup for story_static and week_static
> `do_action_static` OK and Documented

- assets/xml/objects/object_shn.xml
- src/overlays/actors/ovl_En_Shn/z_en_shn.c
- src/overlays/actors/ovl_En_Shn/z_en_shn.h
- src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.c
- src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.h
- tools/disasm/functions.txt
---
This is a much more complicated object than any other Syateki-adjacent object, since it's really three different characters that basically just swap heads. Hopefully, my names and comments make it clear how it works, but please let me know if you're confused.
> Document object_shn (Shooting Gallery Men and Swamp Guide)

- spec
- src/overlays/actors/ovl_Door_Warp1/z_door_warp1.c
---
With the talk of draw functions in the discord, managed to match the rest of door_warp1.
> Door_Warp1 OK

- assets/xml/objects/object_obj_yasi.xml
- src/overlays/actors/ovl_Obj_Yasi/z_obj_yasi.c
- src/overlays/actors/ovl_Obj_Yasi/z_obj_yasi.h
This was the first actor I done, so I'm just finishing this actor off by naming the contents of the object and then use more the descriptive symbols.
> Yasi descriptive names

- include/z64.h
- include/z64player.h
- spec
- src/boot_O2_g3/z_std_dma.c
- src/overlays/actors/ovl_En_Time_Tag/z_en_time_tag.c
- src/overlays/actors/ovl_En_Time_Tag/z_en_time_tag.h
> En_Time_Tag

- include/macros.h
- src/code/flg_set.c
- src/code/z_kaleido_setup.c
- src/code/z_message.c
- src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
- src/overlays/actors/ovl_Boss_02/z_boss_02.c
- src/overlays/actors/ovl_Boss_03/z_boss_03.c
- src/overlays/actors/ovl_En_Fishing/z_en_fishing.c
- src/overlays/actors/ovl_En_Fsn/z_en_fsn.c
- src/overlays/actors/ovl_En_Mag/z_en_mag.c
- src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
- src/overlays/actors/ovl_En_Sob1/z_en_sob1.c
- src/overlays/actors/ovl_En_Tanron2/z_en_tanron2.c
- src/overlays/actors/ovl_En_Test6/z_en_test6.c
- src/overlays/actors/ovl_En_Trt/z_en_trt.c
- src/overlays/gamestates/ovl_select/z_select.c
Change controller macros to take a `GameState*` instead of a `GlobalContext*`.
> Controller Macros Update

- include/functions.h
- spec
- src/code/z_actor.c
- src/overlays/actors/ovl_En_Part/z_en_part.c
- src/overlays/actors/ovl_En_Part/z_en_part.h
First PR, please let me know if there's anything I did wrong.
> `ovl_En_Part` OK

- README.md
- tools/namefixer.py
Just added the comma where it was missing.
> Fix namefixer.py

- assets/xml/objects/gameplay_keep.xml
- src/code/z_en_item00.c
- src/overlays/actors/ovl_En_Box/z_en_box.c
- src/overlays/actors/ovl_En_Elfbub/z_en_elfbub.c
- src/overlays/actors/ovl_En_Elfgrp/z_en_elfgrp.c
- src/overlays/actors/ovl_En_Elforg/z_en_elforg.c
- src/overlays/actors/ovl_En_Elforg/z_en_elforg.h
I noticed this was another example of having the limbs in an external enum rather than in the object, so I went and did that. I also noticed there was no params-packing macro, so I did that too. And while I was working with elforg, I did some very minor cleanup.
> Some minor cleanup involving stray fairies

- spec
- src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag.c
- src/overlays/actors/ovl_En_Okarina_Tag/z_en_okarina_tag.h
This one had some challenging control flow so my inexperience may come through here.
> `ovl_En_Okarina_Tag` OK

- include/PR/gbi.h
- include/PR/mbi.h
- include/libc/stdint.h
- include/ultra64/gs2dex.h
- include/ultra64/vi.h
- include/z64.h
- src/boot_O2_g3/fault.c
- src/code/z_message.c
- src/code/z_room.c
- src/code/z_scene.c
- src/libultra/gu/lookathil.c
- src/libultra/io/contreaddata.c
- src/libultra/io/controller.c
- src/libultra/io/epirawdma.c
- src/libultra/io/visetxscale.c
- src/libultra/os/initialize.c
- src/libultra/rmon/xldtob.c
- src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c
Hex with capital letters. For reference, the regex I used was `0x[0-9a-fA-F]*[a-f][0-9a-fA-F]*` incase we want to double check at a later time
> Hex Cleanup

- include/functions.h
- src/code/PreRender.c
- src/code/z_demo.c
- src/code/z_sram_NES.c
`func_80170798` from `PreRender.c`
`func_800EDBE0` from `z_demo.c`
`Sram_OpenSave` from `z_sram_NES.c`
> Match 3 NON_MATCHINGS from code

- assets/xml/objects/object_mtoride.xml
- assets/xml/overlays/ovl_Dm_Char01.xml
- src/overlays/actors/ovl_Dm_Char01/z_dm_char01.c
Some of these names might not be the best, but if you have any better ideas, just let me know.
> Document object_mtoride (Woodfall scene objects)

- assets/xml/objects/object_lotus.xml
- src/overlays/actors/ovl_Bg_Lotus/z_bg_lotus.c
It's a lily pad; what more can I say?
> Document object_lotus (lily pad)

- assets/xml/objects/object_warp1.xml
- src/overlays/actors/ovl_Door_Warp1/z_door_warp1.c
The limbs on the crystals are kind of hard to name, since they use 20 limbs to display 7 DisplayLists. I tried my best, but I'm open for suggestions.
> Document object_warp1 (blue warp, warp crystal, boss warp)

- assets/xml/objects/object_zos.xml
- src/overlays/actors/ovl_En_Zos/z_en_zos.c
- src/overlays/actors/ovl_En_Zos/z_en_zos.h
- tools/disasm/functions.txt
- tools/disasm/variables.txt
This object was a real pain to document. There are lots of very similar animations in it. I tried my best, but if you don't like any names, I'm happy to discuss.
> Document object_zos (Evan)

- src/overlays/actors/ovl_Bg_Kin2_Fence/z_bg_kin2_fence.c
Elliptic found this and asked someone to PR it quickly, so here we go.
> Better match for BgKin2Fence_CheckHitMask

- include/z64.h
- spec
- src/code/z_actor.c
- src/overlays/actors/ovl_Mir_Ray/z_mir_ray.c
- src/overlays/actors/ovl_Mir_Ray3/z_mir_ray3.c
- Actor_DrawLensActors
- MirRay_ReflectedBeam
- func_80B9E8D4
> Match 3 Functions (z_actor OK, z_mir_ray OK, z_mir_ray3 OK)

- assets/xml/objects/object_dno.xml
- src/overlays/actors/ovl_En_Dnq/z_en_dnq.c
- src/overlays/actors/ovl_En_Dnq/z_en_dnq.h
@emilybrooks and I bashed our heads together on some of the original names, and we couldn't figure out what some of them meant or what the developers meant. I hope it's okay to leave this untranslated.
> object_dno (Deku King) documented

- assets/xml/objects/object_boss_hakugin.xml
- src/overlays/actors/ovl_En_Hakurock/z_en_hakurock.c
I don't *quite* know what to do with that gigantic blob of zeroes, but at the moment I just decided to name it and extract it as a `Blob`. Other than that, this was the easiest boss object to document.
> Document object_boss_hakugin (Goht)

- include/functions.h
- src/code/z_bgcheck.c
- src/overlays/actors/ovl_Bg_Haka_Bombwall/z_bg_haka_bombwall.c
- src/overlays/actors/ovl_Boss_06/z_boss_06.c
Still some nasty stuff left, of course.
> Match 4 functions in BGcheck, remove nonequivalency in DynaPoly_ExpandSRT and BgHakaBombwall

- docs/CONTRIBUTING.md
- format.py
https://discord.com/channels/688807550715560050/915273929369731173/1051633338101800980
> Fix Website 404 and Format script error message

- include/functions.h
- include/z64.h
- include/z64frameadvance.h
- src/code/z_pause.c
Introduces a header for the frame advance system
(I admit this PR feels a bit silly)
> `z64frameadvance.h`

- tools/progress.py
Now accounts for the fact that audio is now its own folder.
As a side note also moves the git import as well as the json import to the else branches where they are used, so you don't have to have them installed if you just run the text version.
Before:
```
./tools/progress.py 
src:      3436256 /  4607696 total bytes decompiled      74.5764%
boot:           78544 /    86064 bytes decompiled      91.2623%
code:          500880 /   926048 bytes decompiled      54.0879% <-----
overlays:     2856832 /  3595584 bytes decompiled      79.4539%
assets:  33033936 / 40816656 total bytes debinarized     80.9325%
archives:           0 /   434608 bytes debinarized      0.0000%
audio:              0 /  6029280 bytes debinarized      0.0000%
interface:     220352 /   801520 bytes debinarized …
```
> Progress Script Hotfix

- assets/xml/objects/object_dt.xml
- src/overlays/actors/ovl_En_Ending_Hero/z_en_ending_hero.c
- src/overlays/actors/ovl_En_Ending_Hero6/z_en_ending_hero6.c
thanks Tharo for helping with the tlut pairings
> [Doc] small, names for mayor dotour's eye and eyebrow textures

- spec
- src/overlays/actors/ovl_En_Tru/z_en_tru.c
(Also touched up other similar functions for uniformity)
> Matched last remaining function in z_en_tru.c.

- src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_collect.c
> Match `KaleidoScope_DrawQuestStatus`

- src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_debug.c
- tools/namefixer.py
Noticed a couple things that should be fixed in namefixer.
> Namefixer Fixes

- spec
- src/overlays/actors/ovl_Object_Kankyo/z_object_kankyo.c
Similar type of trick for the `if (1) {}`'s on whether to break/continue early or not
> Match func_808DDE9C (z_object_kankyo.c OK)

- assets/xml/objects/object_tree.xml
- src/overlays/actors/ovl_Obj_Tree/z_obj_tree.c
Renamed DLists, Textures, and col.
> Tree Asset Decomp for object_tree

- assets/xml/objects/object_snowwd.xml
- src/overlays/actors/ovl_En_Snowwd/z_en_snowwd.c
> object_snowwd

- assets/xml/objects/gameplay_keep.xml
- src/code/z_player_lib.c
- src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
Documents the first portion of gameplay keep (up to the player animations) though leaves out 2 things
* ~~2 unknown blobs~~
* 1 unused texture
* 1 texture that looks to be used with arrows, so will wait for more docs there.
> Some Gameplay keep docs (starts at the top)

- assets/xml/objects/object_dkjail_obj.xml
- assets/xml/objects/object_dor02.xml
- assets/xml/objects/object_dor04.xml
- assets/xml/objects/object_gm.xml
- assets/xml/objects/object_sekihig.xml
- assets/xml/objects/object_sekihil.xml
- assets/xml/objects/object_sekihin.xml
- assets/xml/objects/object_sekihiz.xml
- assets/xml/objects/object_tanron1.xml
- assets/xml/objects/object_tanron4.xml
- assets/xml/objects/object_zog.xml
- src/overlays/actors/ovl_Bg_Dkjail_Ivy/z_bg_dkjail_ivy.c
- src/overlays/actors/ovl_En_Sekihi/z_en_sekihi.c
- src/overlays/actors/ovl_En_Tanron4/z_en_tanron4.c
- src/overlays/actors/ovl_En_Tanron4/z_en_tanron4.h
Goes through some of the partial objects (as well as the two empty objects) and tries to finish/clean them up.
* tanron1
* gm
* tanron4
* sekihi
* dkjail
* dor02
* dor04
> Some partial objects cleanup

- assets/xml/objects/object_ishi.xml
- src/overlays/actors/ovl_En_Ishi/z_en_ishi.c
its a rock theres not a lot to it lol
> document object_ishi

- assets/xml/objects/object_dinofos.xml
- src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.c
- src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.h
> document object_dinofos

- tools/rename_sym.sh
This allows the tool to rename object xml elements with the same tool that is used to variables in src.
> Tools: add assets/xml folder to `rename_sym.sh` directories

- assets/xml/objects/object_tl.xml
- src/overlays/actors/ovl_En_Bigpamet/z_en_bigpamet.c
- src/overlays/actors/ovl_En_Bigpamet/z_en_bigpamet.h
- src/overlays/actors/ovl_En_Kame/z_en_kame.c
- src/overlays/actors/ovl_En_Kame/z_en_kame.h
I want to document the Snapper actors (EnKame and EnBigpamet), so I figured I'd start with their shared object.
> Document object_tl (Snapper)

- assets/xml/objects/object_hana.xml
- src/overlays/actors/ovl_Obj_Hana/z_obj_hana.c
funny object, literally all dls
> document object_hana (graveyard flower)

- assets/xml/objects/object_mkk.xml
- src/overlays/actors/ovl_En_Door/z_en_door.c
- src/overlays/actors/ovl_En_Mkk/z_en_mkk.c
> document object_mkk

- assets/xml/objects/object_zos.xml
- assets/xml/objects/object_zov.xml
- src/overlays/actors/ovl_En_Zos/z_en_zos.c
- src/overlays/actors/ovl_En_Zov/z_en_zov.c
- src/overlays/actors/ovl_En_Zov/z_en_zov.h
some of the names do be weird (like HeadHole for the nondescript holes in their head like i named them ears but then i saw they had actual ears) feel hella dfree to comment and suggest stuff. also there was an unused mouth? its an open mouth but in more of an O shape instead of an A? idk
also fixed a tiny typo in zos actor and object
> document object_zov (lulu the zora vocalist)

- assets/xml/objects/object_fish.xml
- src/overlays/actors/ovl_En_Fishing/z_en_fishing.c
might have forgotten something in the actor code cus its really long and someone had already started to document a lot of stuff there but yea
also i copied a lot of stuff over from the oot xml since it was like identical (i think, the line count was the same if i deleted a single line not in the mm file and the object_fish.c files were pretty similar except for names and some stuff missing from limbs in the oot file) and somewhat documented lol i didnt check all of it but what i checked did match so yea hopefully theyre idk correct
> document object_fish (fishing??) 

- assets/xml/scenes/Z2_00KEIKOKU/Z2_00KEIKOKU.xml
I found out that you can get original cutscene names from MM3D (for those who want to recreate this, go to `romfs/scenes` and find `_info.zsi` files, *not* `_0_info.zsi` files; decompress these files and search for ".jdb"), so I figured I'd get started by picking a scene with a lot of cutscenes. I tried to provide sensible names for these, but it's actually quite hard to think of a short way to summarize a cutscene, so I'm open to suggestions if anyone has any.
> Provide names (and original names) for all Termina Field cutscenes

- docs/tutorial/advanced_control_flow.md
- docs/tutorial/documenting.md
- docs/tutorial/introduction.md
- docs/tutorial/other_functions.md
Just runs namefixer on main so that the docs folder gets updated.
> Docs namefixer

- assets/xml/objects/object_funen.xml
- src/overlays/actors/ovl_Obj_Funen/z_obj_funen.c
> Stone Tower Smoke

- Jenkinsfile
- README.md
- docs/CONTRIBUTING.md
- docs/REVIEWING.md
- docs/tutorial/beginning_decomp.md
- docs/tutorial/data.md
- docs/tutorial/diff_and_permuter.md
- docs/tutorial/draw_functions.md
- docs/tutorial/intro_to_git.md
- docs/tutorial/merging.md
- docs/tutorial/object_decomp.md
I believe this is the only change we would need to make in the repo itself if we want to switch over to `main`. Please let me know if I missed something. Opening as draft until we decide we 100% want to change.
> master to main rename

- spec
- src/overlays/actors/ovl_Bg_Lotus/z_bg_lotus.c
- src/overlays/actors/ovl_Bg_Lotus/z_bg_lotus.h
> ovl_Bg_Lotus decompiled

- assets/xml/objects/object_ha.xml
- src/overlays/actors/ovl_En_Horse/z_en_horse.c
- src/overlays/actors/ovl_En_Horse/z_en_horse.h
i didnt mess with the `limbIndex`es cus `z_en_horse.c` is used by other stuff like epona apparently
also it brought commits from the other branch as well?? wat (edit: fixed)
> document object_ha (donkeys)

- assets/xml/objects/object_mk.xml
- src/overlays/actors/ovl_En_Mk/z_en_mk.c
- src/overlays/actors/ovl_En_Mk/z_en_mk.h
My first pr to a decomp project :)
> Document object_mk

- assets/xml/objects/object_zl1.xml
> object_zl1

- assets/xml/objects/object_comb.xml
- src/overlays/actors/ovl_Obj_Comb/z_obj_comb.c
> object_comb

- assets/xml/objects/object_icicle.xml
- src/overlays/actors/ovl_Bg_Icicle/z_bg_icicle.c
> object_icicle

- assets/xml/objects/object_big_fwall.xml
- src/overlays/actors/ovl_En_Encount3/z_en_encount3.c
object_big_fwall.xml / z_en_encount3.c update
> obj_big_fwall

- assets/xml/objects/object_visiblock.xml
- src/overlays/actors/ovl_Obj_Visiblock/z_obj_visiblock.c
Object for the Lens of Truth Platforms
> Obj_visiblock

- src/code/z_camera.c
The stack is really stubborn on this function. But it's equivalent now
> Match `Camera_Normal1`

- include/z64camera.h
- src/code/z_camera.c
Also copied some basic docs from OoT
> Match `Camera_Battle1`

- tools/progress.py
fixes the progress script to work with both newer (>= 2.40) and older LD versions.
> Progress LD fix

- assets/xml/objects/object_owl.xml
- src/overlays/actors/ovl_En_Owl/z_en_owl.c
- src/overlays/actors/ovl_En_Owl/z_en_owl.h
Object for Kaepora Gaebora (Owl)
> object_owl

- assets/xml/objects/object_test3.xml
- src/overlays/actors/ovl_En_Test3/z_en_test3.c
> object_test3 (kafei)

- assets/xml/objects/object_boss05.xml
Similar to what I did with the Garo object, I split this one out to make the eventual actor PR a little smaller. I do think this object may have a bit of controversy around the term "head", though I hope I explained my position well enough in the comments.
> Document `object_boss05` (Bio Deku Baba)

- src/code/z_sram_NES.c
> Match `Sram_CopySave`

- src/code/z_message_staff.c
> Match `Message_DrawTextCredits` (z_message_staff OK)

- src/code/z_kankyo.c
If you want a good laugh, look at the first commit I made which was the first really fake match I found. Thankfully I was able to find something a bit better.
> Match `Environment_Init`

- include/z64environment.h
- src/audio/lib/data.c
- src/boot/yaz0.c
- src/code/z_common_data.c
- src/code/z_message.c
- src/code/z_parameter.c
- src/code/z_player_lib.c
- src/libultra/io/motor.c
- src/overlays/actors/ovl_En_Dnh/z_en_dnh.c
- src/overlays/actors/ovl_En_Tanron2/z_en_tanron2.c
- src/overlays/actors/ovl_En_Test3/z_en_test3.c
- src/overlays/gamestates/ovl_file_choose/z_file_choose_NES.c
- src/overlays/gamestates/ovl_file_choose/z_file_nameset_NES.c
- tools/disasm/variables.txt
I'm trying to address a few issues that I noted while testing building with modern gcc.
I fixed a few issues like functions having the wrong return type or using the wrong member of a struct.
There are some other issues that we can't solve without breaking matching, like every comment I made in `z_message.c`.
I also added a few `ALIGNED` on some variables that needs an specific alignment to avoid breaking on shifted scenarios.
> Misc fixes 1

- src/code/z_camera.c
Just some low-hanging fruit docs for camera, and a small number of Fake match fixes
> Misc Camera Cleanup

- src/code/z_scene.c
- src/overlays/actors/ovl_Dm_Char02/z_dm_char02.c
- src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
- src/overlays/actors/ovl_En_Am/z_en_am.c
- src/overlays/actors/ovl_En_Baguo/z_en_baguo.c
- src/overlays/actors/ovl_En_Bal/z_en_bal.c
- src/overlays/actors/ovl_En_Bb/z_en_bb.c
- src/overlays/actors/ovl_En_Bbfall/z_en_bbfall.c
- src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
- src/overlays/actors/ovl_En_Kaizoku/z_en_kaizoku.c
- src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
- src/overlays/actors/ovl_En_Nb/z_en_nb.c
- src/overlays/actors/ovl_En_Nb/z_en_nb.h
- src/overlays/actors/ovl_En_Neo_Reeba/z_en_neo_reeba.c
- src/overlays/actors/ovl_En_Nimotsu/z_en_nimotsu.c
- src/overlays/actors/ovl_En_Niw/z_en_niw.c
- src/overlays/actors/ovl_En_Niw/z_en_niw.h
- src/overlays/actors/ovl_En_Nutsball/z_en_nutsball.c
- src/overlays/actors/ovl_En_Nwc/z_en_nwc.c
- src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
- src/overlays/actors/ovl_En_Syateki_Wf/z_en_syateki_wf.c
- src/overlays/actors/ovl_En_Tite/z_en_tite.c
- src/overlays/actors/ovl_En_Trt2/z_en_trt2.c
> Animation Cleanup: En_N*

- assets/xml/archives/icon_item_24_static.xml
Switched lines for gQuestIconSmallMagicJarTex and gQuestIconSmallKeyTex in icon_item_24_static.xml.
> Switched icon_item_24_static.xml lines for 0x6300 and 0x5A00

- Jenkinsfile
Jenkins requires this to be able to report progress on the main branch
> Install GitPython in Jenkins

- include/romfile.h
- include/segment_symbols.h
- include/z64actor_dlftbls.h
- include/z64dma.h
- include/z64effect_ss.h
- include/z64game.h
- include/z64pause_menu.h
- include/z64transition.h
- src/boot/z_std_dma.c
- src/code/graph.c
- src/code/z_DLF.c
- src/code/z_actor.c
- src/code/z_actor_dlftbls.c
- src/code/z_effect_soft_sprite.c
- src/code/z_effect_soft_sprite_dlftbls.c
- src/code/z_fbdemo_dlftbls.c
- src/code/z_game_dlftbls.c
- src/code/z_kaleido_manager.c
- src/code/z_overlay.c
- src/dmadata/dmadata.c
MM's version of https://github.com/zeldaret/oot/pull/1742
> Use Romfile in place of vromStart and vromEnd in structs

- Makefile
- include/rom_header.h
- tools/disasm/disasm.py
Extracts the rom_header in the new format adopted by OoT in https://github.com/zeldaret/oot/pull/1932.
> New Romheader format

- tools/warnings_count/check_new_warnings.sh
Forgot to update this with the new build system
> warnings_count fix

- Makefile
- tools/disasm/disasm.py
see https://github.com/zeldaret/oot/pull/1935
Fixes building for MacOS https://discord.com/channels/688807550715560050/688851976746041391/1243711438443249684
> Use `gcc -E` for `cpp`

- assets/xml/objects/object_b_heart.xml
This change continues the work done by obj_b_heart #1424 
I agree to my contributions in this PR to be under a CC0 license.
> obj_b_heart documentation continuation

- include/PR/gbi.h
This PR updates the gbi.h point lighting implementation to be more complete.
- Wraps all of the point lighting features in a macro to clearly identify it.
- Adds comments to the `PointLight_t` structure describing the fields.
- Adds `G_LIGHTING_POSITIONAL_H`, for completeness.
- Cleans up the `gdSPDefLights*` macros
- Adds `gdSPDefPointLights` macros, for completeness.
> Cleanup the point lighting gbi implementation

- assets/xml/objects/object_bba.xml
- assets/xml/objects/object_bob.xml
- assets/xml/objects/object_cne.xml
- src/code/z_en_hy_code.c
- src/overlays/actors/ovl_En_Baba/z_en_baba.c
- src/overlays/actors/ovl_En_Baba/z_en_baba.h
- src/overlays/actors/ovl_En_Bba_01/z_en_bba_01.c
- src/overlays/actors/ovl_En_Cne_01/z_en_cne_01.c
Documents object_bob which is the object file for an unused NPC leftover from OoT.
Also gives better prefixes to object_cne and object_bba.
> Document object_bob

- src/audio/lib/seqplayer.c
Same case as in https://github.com/zeldaret/oot/pull/1996, thought it makes more sense this way
> Cleaner AudioScript_SequenceChannelProcessScript Match

- include/audiomgr.h
- include/idle.h
- include/irqmgr.h
- include/main.h
- include/padmgr.h
- include/scheduler.h
- include/segmented_address.h
- include/z64.h
- include/z64player.h
- src/boot/idle.c
- src/code/main.c
- src/code/padmgr.c
- src/code/speed_meter.c
- src/code/z_jpeg.c
- src/code/z_lib.c
- src/code/z_nulltask.c
Companion PR to https://github.com/zeldaret/oot/pull/2151
> [headers] Move padmgr, scheduler, irqmgr symbols to respective headers; add segmented_address.h

- include/kaleido_manager.h
- include/z64.h
- include/z64jpeg.h
- include/z64pause_menu.h
- src/code/game.c
- src/code/jpegdecoder.c
- src/code/z_kaleido_manager.c
- src/code/z_kaleido_scope_call.c
- src/code/z_player_call.c
Sync with oot:
- https://github.com/zeldaret/oot/pull/2171
- https://github.com/zeldaret/oot/pull/2174
> [headers] Add kaleido_manager.h, clean up z64jpeg.h protos

- Makefile
For context see:
- https://github.com/zeldaret/oot/pull/1979
- https://github.com/zeldaret/oot/pull/1995
> Promote some CC_CHECK warnings to errors

- include/gfx.h
- include/gfx_setupdl.h
- include/z64.h
- include/z64skin_matrix.h
Companion PR to https://github.com/zeldaret/oot/pull/2221
> [headers] gfx_setupdl.h and (fixup) z64skin_matrix.h

- include/zelda_arena.h
- src/code/speed_meter.c
- src/code/z_actor.c
- src/code/z_camera.c
- src/code/z_collision_check.c
- src/code/z_effect_soft_sprite.c
- src/code/z_fcurve_data_skelanime.c
- src/code/z_malloc.c
- src/code/z_overlay.c
- src/code/z_parameter.c
- src/code/z_play.c
- src/code/z_play_hireso.c
- src/code/z_skelanime.c
- src/code/z_skin_awb.c
- src/overlays/actors/ovl_En_Test3/z_en_test3.c
- src/overlays/actors/ovl_En_Test6/z_en_test6.c
- src/overlays/actors/ovl_player_actor/z_player.c
Companion PR to oot PR https://github.com/zeldaret/oot/pull/2248
> [headers] `z64malloc.h` -> `zelda_arena.h`

- include/z64object.h
- include/z64play.h
- include/z64player.h
- include/z64scene.h
Companion PR to oot PR https://github.com/zeldaret/oot/pull/2250
> [headers] Move object decls to z64object.h, cleanup `Scene_Command*` protos

- include/z64actor.h
- src/code/z_actor.c
- src/overlays/actors/ovl_En_Am/z_en_am.c
- src/overlays/actors/ovl_En_Bb/z_en_bb.c
- src/overlays/actors/ovl_En_Bbfall/z_en_bbfall.c
- src/overlays/actors/ovl_En_Dekubaba/z_en_dekubaba.c
- src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.c
- src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
- src/overlays/actors/ovl_En_Nutsball/z_en_nutsball.c
- src/overlays/actors/ovl_En_Okuta/z_en_okuta.c
- src/overlays/actors/ovl_En_Peehat/z_en_peehat.c
- src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.c
- src/overlays/actors/ovl_En_Poh/z_en_poh.c
- src/overlays/actors/ovl_En_St/z_en_st.c
- src/overlays/actors/ovl_En_Tite/z_en_tite.c
- src/overlays/actors/ovl_player_actor/z_player.c
See https://github.com/zeldaret/oot/pull/2276
> Document `ACTOR_FLAG_SFX_FOR_PLAYER_BODY_HIT`

- Makefile
Ports over the fix from https://github.com/zeldaret/oot/pull/2370
I haven't checked if there are other issues when building on macOS tho, since I don't have one.
> Port over macOS fix

- Dockerfile
- increased parity with OOO project
- updated to latest Ubuntu LTS version
- removed redundant build layers
- fixed Docker console warnings
- tested and confirmed OK with local Docker build
> Updated Docker Image

- src/overlays/actors/ovl_Obj_Syokudai/z_obj_syokudai.c
While looking for something else noticed this.
> `En_Syokudai`: label one arrow type enum

- src/code/z_map_disp.c
- src/overlays/actors/ovl_Bg_Dblue_Balance/z_bg_dblue_balance.c
- src/overlays/actors/ovl_Bg_Hakugin_Elvpole/z_bg_hakugin_elvpole.c
- src/overlays/actors/ovl_En_Firefly/z_en_firefly.h
> Small Misc fix cleanups

- tools/fix_bss.py
Brings over OoT's version that has a few fixes.
> Fix_bss script update and fixes
